function [testPrediction,bestLambda] = ...
    groupedRidgePrediction( ...
    X,y,groupID,outerTrainMask, ...
    outerTestMask,lambdaGrid)

    trainingCases = unique( ...
        groupID(outerTrainMask));

    validationMAE = nan( ...
        numel(lambdaGrid),1);

    for lambdaIndex = 1:numel(lambdaGrid)

        currentLambda = ...
            lambdaGrid(lambdaIndex);

        validationPrediction = ...
            nan(size(y));

        for caseIndex = 1:numel(trainingCases)

            validationCase = ...
                trainingCases(caseIndex);

            innerValidationMask = ...
                outerTrainMask & ...
                groupID == validationCase;

            innerTrainingMask = ...
                outerTrainMask & ...
                groupID ~= validationCase;

            validationPrediction( ...
                innerValidationMask) = ...
                fitRidgeAndPredict( ...
                X(innerTrainingMask,:), ...
                y(innerTrainingMask), ...
                X(innerValidationMask,:), ...
                currentLambda);
        end

        validationMAE(lambdaIndex) = ...
            mean(abs( ...
            y(outerTrainMask)- ...
            validationPrediction(outerTrainMask)));
    end

    [~,bestIndex] = min(validationMAE);

    bestLambda = ...
        lambdaGrid(bestIndex);

    testPrediction = ...
        fitRidgeAndPredict( ...
        X(outerTrainMask,:), ...
        y(outerTrainMask), ...
        X(outerTestMask,:), ...
        bestLambda);
end