paperRoot = fileparts(mfilename('fullpath'));
clear;
clc;
close all;

%% 1. 读取特征表
resultFolder = fullfile(paperRoot, 'mill', 'results');

dataFile = fullfile( ...
    resultFolder, ...
    "run_level_features.mat");

loadedData = load(dataFile);
featureTable = loadedData.featureTable;

%% 2. 提取数据
y = featureTable.VB;
caseID = featureTable.CaseID;
runID = featureTable.RunID;
originalIndex = featureTable.OriginalIndex;

% 加工条件
XProcess = featureTable{:, ...
    {'DOC','Feed','Material'}};

% 第8列以后是78个传感器特征
XSensor = featureTable{:,8:end};

% 加工条件与传感器特征合并
XCombined = [XProcess XSensor];

nSamples = height(featureTable);
caseList = unique(caseID);

%% 3. 初始化预测结果
predMean = nan(nSamples,1);
predProcess = nan(nSamples,1);
predSensorRidge = nan(nSamples,1);
predCombinedRidge = nan(nSamples,1);

bestLambdaSensor = nan(numel(caseList),1);
bestLambdaCombined = nan(numel(caseList),1);

% 岭回归候选参数
lambdaGrid = logspace(-4,4,17);

%% 4. 外层留一案例验证
for k = 1:numel(caseList)

    testCase = caseList(k);

    testMask = caseID == testCase;
    trainMask = ~testMask;

    fprintf( ...
        "正在测试Case %d：训练%d条，测试%d条\n", ...
        testCase,sum(trainMask),sum(testMask));

    %% 模型1：训练集均值
    predMean(testMask) = mean(y(trainMask));

    %% 模型2：只使用加工参数
    processModel = fitlm( ...
        XProcess(trainMask,:), ...
        y(trainMask));

    predProcess(testMask) = predict( ...
        processModel, ...
        XProcess(testMask,:));

    %% 模型3：只使用传感器特征的岭回归
    [predSensorRidge(testMask), ...
        bestLambdaSensor(k)] = groupedRidgePrediction( ...
        XSensor, ...
        y, ...
        caseID, ...
        trainMask, ...
        testMask, ...
        lambdaGrid);

    %% 模型4：加工条件与传感器特征
    [predCombinedRidge(testMask), ...
        bestLambdaCombined(k)] = groupedRidgePrediction( ...
        XCombined, ...
        y, ...
        caseID, ...
        trainMask, ...
        testMask, ...
        lambdaGrid);
end

%% 5. 计算总体指标
modelNames = [ ...
    "Training mean", ...
    "Process only", ...
    "Sensor ridge", ...
    "Process + sensor ridge"];

predictionMatrix = [ ...
    predMean, ...
    predProcess, ...
    predSensorRidge, ...
    predCombinedRidge];

MAE = nan(numel(modelNames),1);
RMSE = nan(numel(modelNames),1);
R2 = nan(numel(modelNames),1);

for m = 1:numel(modelNames)
    [MAE(m),RMSE(m),R2(m)] = ...
        calculateRegressionMetrics( ...
        y,predictionMatrix(:,m));
end

overallResults = table( ...
    modelNames',MAE,RMSE,R2, ...
    'VariableNames', ...
    {'Model','MAE','RMSE','R2'});

fprintf("\n========== 留一案例总体结果 ==========\n");
disp(overallResults);

%% 6. 计算每个案例的MAE
caseMAE = nan(numel(caseList),numel(modelNames));
caseSampleCount = nan(numel(caseList),1);

for k = 1:numel(caseList)
    mask = caseID == caseList(k);

    caseSampleCount(k) = sum(mask);

    for m = 1:numel(modelNames)
        caseMAE(k,m) = mean( ...
            abs(y(mask)-predictionMatrix(mask,m)));
    end
end

caseResults = table( ...
    caseList, ...
    caseSampleCount, ...
    caseMAE(:,1), ...
    caseMAE(:,2), ...
    caseMAE(:,3), ...
    caseMAE(:,4), ...
    'VariableNames', ...
    {'CaseID','SampleCount','MeanModelMAE', ...
     'ProcessModelMAE','SensorRidgeMAE', ...
     'CombinedRidgeMAE'});

fprintf("\n========== 每个案例的MAE ==========\n");
disp(caseResults);

%% 7. 保存逐样本预测结果
predictionTable = table( ...
    originalIndex,caseID,runID,y, ...
    predMean,predProcess, ...
    predSensorRidge,predCombinedRidge, ...
    'VariableNames', ...
    {'OriginalIndex','CaseID','RunID','ActualVB', ...
     'PredMean','PredProcess','PredSensorRidge', ...
     'PredCombinedRidge'});

%% 8. 绘制真实值与预测值
figure( ...
    "Color","w", ...
    "Position",[100 100 1200 900]);

tiledlayout(2,2, ...
    "TileSpacing","compact", ...
    "Padding","compact");

minimumValue = min([y;predictionMatrix(:)]);
maximumValue = max([y;predictionMatrix(:)]);

for m = 1:numel(modelNames)

    nexttile;

    scatter( ...
        y,predictionMatrix(:,m), ...
        35,caseID,"filled");

    hold on;

    plot( ...
        [minimumValue maximumValue], ...
        [minimumValue maximumValue], ...
        "k--","LineWidth",1.2);

    hold off;
    grid on;
    axis square;

    xlim([minimumValue maximumValue]);
    ylim([minimumValue maximumValue]);

    xlabel("Actual VB");
    ylabel("Predicted VB");

    title( ...
        modelNames(m)+ ...
        ", MAE="+sprintf("%.3f",MAE(m))+ ...
        ", R^2="+sprintf("%.3f",R2(m)));

    colorbar;
end

sgtitle("Leave-One-Case-Out Baseline Results");

%% 9. 绘制每个案例的MAE
figure( ...
    "Color","w", ...
    "Position",[100 100 1300 600]);

bar(caseList,caseMAE,"grouped");

grid on;
xlabel("Test Case");
ylabel("MAE");
title("MAE for Each Held-Out Case");
legend(modelNames,"Location","northwest");

%% 10. 保存结果
writetable( ...
    overallResults, ...
    fullfile(resultFolder, ...
    "baseline_overall_results.csv"));

writetable( ...
    caseResults, ...
    fullfile(resultFolder, ...
    "baseline_case_results.csv"));

writetable( ...
    predictionTable, ...
    fullfile(resultFolder, ...
    "baseline_predictions.csv"));

save( ...
    fullfile(resultFolder, ...
    "baseline_results.mat"), ...
    "overallResults", ...
    "caseResults", ...
    "predictionTable", ...
    "bestLambdaSensor", ...
    "bestLambdaCombined", ...
    "lambdaGrid");

fprintf("\n结果已保存到：\n%s\n",resultFolder);

%% 局部函数1：带内层分组验证的岭回归
function [testPrediction,bestLambda] = ...
    groupedRidgePrediction( ...
    X,y,groupID,outerTrainMask, ...
    outerTestMask,lambdaGrid)

    trainingCases = unique( ...
        groupID(outerTrainMask));

    validationMAE = nan( ...
        numel(lambdaGrid),1);

    for lambdaIndex = 1:numel(lambdaGrid)

        currentLambda = ...
            lambdaGrid(lambdaIndex);

        validationPrediction = ...
            nan(size(y));

        for caseIndex = 1:numel(trainingCases)

            validationCase = ...
                trainingCases(caseIndex);

            innerValidationMask = ...
                outerTrainMask & ...
                groupID == validationCase;

            innerTrainingMask = ...
                outerTrainMask & ...
                groupID ~= validationCase;

            validationPrediction( ...
                innerValidationMask) = ...
                fitRidgeAndPredict( ...
                X(innerTrainingMask,:), ...
                y(innerTrainingMask), ...
                X(innerValidationMask,:), ...
                currentLambda);
        end

        validationMAE(lambdaIndex) = ...
            mean(abs( ...
            y(outerTrainMask)- ...
            validationPrediction(outerTrainMask)));
    end

    [~,bestIndex] = min(validationMAE);
    bestLambda = lambdaGrid(bestIndex);

    testPrediction = fitRidgeAndPredict( ...
        X(outerTrainMask,:), ...
        y(outerTrainMask), ...
        X(outerTestMask,:), ...
        bestLambda);
end

%% 局部函数2：训练岭回归并预测
function yPrediction = ...
    fitRidgeAndPredict( ...
    XTrain,yTrain,XTest,lambda)

    featureMean = mean(XTrain,1);
    featureStd = std(XTrain,[],1);

    % 移除在当前训练集中没有变化的特征
    keepFeature = ...
        isfinite(featureStd) & ...
        featureStd > 1e-12;

    XTrain = XTrain(:,keepFeature);
    XTest = XTest(:,keepFeature);

    featureMean = featureMean(keepFeature);
    featureStd = featureStd(keepFeature);

    XTrainStandardized = ...
        (XTrain-featureMean)./featureStd;

    XTestStandardized = ...
        (XTest-featureMean)./featureStd;

    responseMean = mean(yTrain);
    yCentered = yTrain-responseMean;

    nFeatures = size( ...
        XTrainStandardized,2);

    beta = ( ...
        XTrainStandardized' * ...
        XTrainStandardized + ...
        lambda*eye(nFeatures)) \ ...
        (XTrainStandardized' * ...
        yCentered);

    yPrediction = ...
        responseMean + ...
        XTestStandardized*beta;
end

%% 局部函数3：计算回归指标
function [MAE,RMSE,R2] = ...
    calculateRegressionMetrics( ...
    actual,predicted)

    validMask = ...
        isfinite(actual) & ...
        isfinite(predicted);

    actual = actual(validMask);
    predicted = predicted(validMask);

    residual = actual-predicted;

    MAE = mean(abs(residual));
    RMSE = sqrt(mean(residual.^2));

    totalSumSquares = ...
        sum((actual-mean(actual)).^2);

    residualSumSquares = ...
        sum(residual.^2);

    R2 = 1- ...
        residualSumSquares/ ...
        totalSumSquares;
end