paperRoot = fileparts(mfilename('fullpath'));
clear;
clc;
close all;

resultFolder = ...
    fullfile(paperRoot, 'mill', 'results');

%% 1. 加载结果
baselineData = load( ...
    fullfile(resultFolder, ...
    "baseline_results.mat"));

featureData = load( ...
    fullfile(resultFolder, ...
    "run_level_features.mat"));

predictionTable = ...
    baselineData.predictionTable;

featureTable = ...
    featureData.featureTable;

%% 2. 加入加工参数
diagnosticTable = predictionTable;

diagnosticTable.DOC = featureTable.DOC;
diagnosticTable.Feed = featureTable.Feed;
diagnosticTable.Material = featureTable.Material;

%% 3. 计算最佳模型的误差
diagnosticTable.Residual = ...
    diagnosticTable.PredCombinedRidge - ...
    diagnosticTable.ActualVB;

diagnosticTable.AbsoluteError = ...
    abs(diagnosticTable.Residual);

%% 4. 按绝对误差降序排列
diagnosticTable = sortrows( ...
    diagnosticTable, ...
    "AbsoluteError", ...
    "descend");

fprintf("========== 误差最大的15条记录 ==========\n");

disp(diagnosticTable(1:15,{ ...
    'OriginalIndex', ...
    'CaseID', ...
    'RunID', ...
    'ActualVB', ...
    'PredCombinedRidge', ...
    'Residual', ...
    'AbsoluteError', ...
    'DOC', ...
    'Feed', ...
    'Material'}));

%% 5. 根据实际磨损量划分三个区间
actualVB = predictionTable.ActualVB;
predictedVB = predictionTable.PredCombinedRidge;

wearGroup = strings(height(predictionTable),1);

wearGroup(actualVB < 0.2) = "VB < 0.2";
wearGroup(actualVB >= 0.2 & actualVB < 0.4) = ...
    "0.2 <= VB < 0.4";
wearGroup(actualVB >= 0.4) = "VB >= 0.4";

groupNames = unique(wearGroup,"stable");

SampleCount = nan(numel(groupNames),1);
GroupMAE = nan(numel(groupNames),1);
GroupRMSE = nan(numel(groupNames),1);
MeanResidual = nan(numel(groupNames),1);

for k = 1:numel(groupNames)

    mask = wearGroup == groupNames(k);

    residual = predictedVB(mask)-actualVB(mask);

    SampleCount(k) = sum(mask);
    GroupMAE(k) = mean(abs(residual));
    GroupRMSE(k) = sqrt(mean(residual.^2));
    MeanResidual(k) = mean(residual);
end

wearGroupResults = table( ...
    groupNames, ...
    SampleCount, ...
    GroupMAE, ...
    GroupRMSE, ...
    MeanResidual, ...
    'VariableNames', ...
    {'WearGroup','SampleCount','MAE', ...
     'RMSE','MeanResidual'});

fprintf("\n========== 不同磨损区间的误差 ==========\n");
disp(wearGroupResults);

fprintf( ...
    '\nMeanResidual小于0表示模型整体低估，大于0表示模型整体高估。\n');

%% 6. 检查不同案例选择的岭参数
caseList = unique(featureTable.CaseID);

lambdaTable = table( ...
    caseList, ...
    baselineData.bestLambdaSensor, ...
    baselineData.bestLambdaCombined, ...
    'VariableNames', ...
    {'TestCase','SensorLambda', ...
     'CombinedLambda'});

fprintf("\n========== 每个外层案例的最佳Lambda ==========\n");
disp(lambdaTable);

%% 7. 保存诊断结果
writetable( ...
    diagnosticTable, ...
    fullfile(resultFolder, ...
    "ridge_residual_diagnostics.csv"));

writetable( ...
    wearGroupResults, ...
    fullfile(resultFolder, ...
    "ridge_wear_group_results.csv"));

writetable( ...
    lambdaTable, ...
    fullfile(resultFolder, ...
    "ridge_lambda_results.csv"));
%% 8. 分析OriginalIndex 109的特征分布偏移
targetOriginalIndex = 109;

targetMask = ...
    featureTable.OriginalIndex == targetOriginalIndex;

targetCase = featureTable.CaseID(targetMask);

% 组合加工参数和传感器特征
XCombined = [ ...
    featureTable{:,{'DOC','Feed','Material'}}, ...
    featureTable{:,8:end}];

combinedFeatureNames = [ ...
    "DOC", ...
    "Feed", ...
    "Material", ...
    string(featureTable.Properties.VariableNames(8:end))];

% 必须排除目标案例，模拟当时的训练集
trainingMask = ...
    featureTable.CaseID ~= targetCase;

trainingMean = mean( ...
    XCombined(trainingMask,:),1);

trainingStd = std( ...
    XCombined(trainingMask,:),[],1);

trainingStd(trainingStd < 1e-12) = 1;

targetZScore = ( ...
    XCombined(targetMask,:) - ...
    trainingMean) ./ trainingStd;

[sortedAbsoluteZ,sortOrder] = ...
    sort(abs(targetZScore), ...
    "descend");

topCount = min(15,numel(sortOrder));
topIndices = sortOrder(1:topCount);

featureShiftTable = table( ...
    combinedFeatureNames(topIndices)', ...
    targetZScore(topIndices)', ...
    sortedAbsoluteZ(1:topCount)', ...
    'VariableNames', ...
    {'Feature','ZScore','AbsoluteZScore'});

fprintf( ...
    "\n========== OriginalIndex 109偏移最大的特征 ==========\n");

disp(featureShiftTable);

writetable( ...
    featureShiftTable, ...
    fullfile(resultFolder, ...
    "index109_feature_shift.csv"));