paperRoot = fileparts(mfilename('fullpath'));
clear;
clc;
close all;

%% 1. 读取数据
filePath = ...
    fullfile(paperRoot, 'mill', 'mill.mat');

resultFolder = ...
    fullfile(paperRoot, 'mill', 'results');

raw = load(filePath);
mill = raw.mill;

qualityData = load( ...
    fullfile(resultFolder, ...
    "quality_aware_features.mat"));

T = qualityData.qualityAwareTable;

nSamples = height(T);

%% 2. 提取原始time及相对起始时间
MachiningTime = nan(nSamples,1);
ElapsedTime = nan(nSamples,1);

for row = 1:nSamples

    sourceIndex = T.OriginalIndex(row);
    currentCase = T.CaseID(row);

    MachiningTime(row) = ...
        mill(sourceIndex).time;

    % 使用该Case全部原始记录确定起始时间
    allCaseIndices = find( ...
        arrayfun(@(x) ...
        ~isempty(x.case) && ...
        x.case == currentCase, ...
        mill));

    caseTimes = nan( ...
        numel(allCaseIndices),1);

    for j = 1:numel(allCaseIndices)

        currentTime = ...
            mill(allCaseIndices(j)).time;

        if ~isempty(currentTime) && ...
                isfinite(currentTime)

            caseTimes(j) = currentTime;
        end
    end

    caseStartTime = min( ...
        caseTimes,[],"omitnan");

    ElapsedTime(row) = ...
        MachiningTime(row)-caseStartTime;
end

%% 3. 加入表格
timeAwareTable = T;

timeAwareTable.MachiningTime = ...
    MachiningTime;

timeAwareTable.ElapsedTime = ...
    ElapsedTime;

fprintf("========== 时间字段总体检查 ==========\n");
fprintf("缺失MachiningTime数量：%d\n", ...
    sum(~isfinite(MachiningTime)));
fprintf("缺失ElapsedTime数量：%d\n", ...
    sum(~isfinite(ElapsedTime)));
fprintf("MachiningTime范围：%.4f ～ %.4f\n", ...
    min(MachiningTime),max(MachiningTime));
fprintf("ElapsedTime范围：%.4f ～ %.4f\n", ...
    min(ElapsedTime),max(ElapsedTime));

%% 4. 每个案例检查
caseList = unique(T.CaseID);
nCases = numel(caseList);

SampleCount = nan(nCases,1);
TimeMinimum = nan(nCases,1);
TimeMaximum = nan(nCases,1);
ElapsedMaximum = nan(nCases,1);
TimeMonotonic = false(nCases,1);
SpearmanTimeVB = nan(nCases,1);
SpearmanElapsedVB = nan(nCases,1);

for k = 1:nCases

    mask = T.CaseID == caseList(k);

    currentRun = T.RunID(mask);
    currentTime = MachiningTime(mask);
    currentElapsed = ElapsedTime(mask);
    currentVB = T.VB(mask);

    [currentRun,order] = sort(currentRun);

    currentTime = currentTime(order);
    currentElapsed = currentElapsed(order);
    currentVB = currentVB(order);

    SampleCount(k) = numel(currentRun);

    TimeMinimum(k) = min(currentTime);
    TimeMaximum(k) = max(currentTime);
    ElapsedMaximum(k) = max(currentElapsed);

    TimeMonotonic(k) = ...
        all(diff(currentTime) >= 0);

    if numel(currentVB) >= 3 && ...
            std(currentTime) > 0

        SpearmanTimeVB(k) = corr( ...
            currentTime,currentVB, ...
            "Type","Spearman", ...
            "Rows","complete");
    end

    if numel(currentVB) >= 3 && ...
            std(currentElapsed) > 0

        SpearmanElapsedVB(k) = corr( ...
            currentElapsed,currentVB, ...
            "Type","Spearman", ...
            "Rows","complete");
    end
end

caseTimeSummary = table( ...
    caseList,SampleCount, ...
    TimeMinimum,TimeMaximum, ...
    ElapsedMaximum,TimeMonotonic, ...
    SpearmanTimeVB, ...
    SpearmanElapsedVB, ...
    'VariableNames', ...
    {'CaseID','SampleCount', ...
     'TimeMinimum','TimeMaximum', ...
     'ElapsedMaximum','TimeMonotonic', ...
     'SpearmanTimeVB', ...
     'SpearmanElapsedVB'});

fprintf("\n========== 每个案例时间检查 ==========\n");
disp(caseTimeSummary);

%% 5. 总体相关性
overallSpearmanTime = corr( ...
    MachiningTime,T.VB, ...
    "Type","Spearman", ...
    "Rows","complete");

overallSpearmanElapsed = corr( ...
    ElapsedTime,T.VB, ...
    "Type","Spearman", ...
    "Rows","complete");

fprintf("\n总体MachiningTime-VB Spearman相关：%.4f\n", ...
    overallSpearmanTime);

fprintf("总体ElapsedTime-VB Spearman相关：%.4f\n", ...
    overallSpearmanElapsed);

%% 6. 绘制每个案例的时间—磨损关系
fig = figure( ...
    "Color","w", ...
    "Position",[80 40 1300 900]);

tiledlayout(4,4, ...
    "TileSpacing","compact", ...
    "Padding","compact");

for k = 1:nCases

    mask = T.CaseID == caseList(k);

    currentElapsed = ...
        ElapsedTime(mask);

    currentVB = T.VB(mask);

    [currentElapsed,order] = ...
        sort(currentElapsed);

    currentVB = currentVB(order);

    nexttile;

    plot( ...
        currentElapsed,currentVB, ...
        "o-","LineWidth",1.1);

    grid on;
    xlabel("Elapsed time");
    ylabel("VB");

    title( ...
        "Case "+string(caseList(k))+ ...
        ", \rho="+ ...
        sprintf("%.2f", ...
        SpearmanElapsedVB(k)));
end

sgtitle("Elapsed Machining Time versus Tool Wear");

%% 7. 保存
save( ...
    fullfile(resultFolder, ...
    "quality_aware_with_time.mat"), ...
    "timeAwareTable", ...
    "caseTimeSummary", ...
    "overallSpearmanTime", ...
    "overallSpearmanElapsed");

writetable( ...
    timeAwareTable, ...
    fullfile(resultFolder, ...
    "quality_aware_with_time.csv"));

writetable( ...
    caseTimeSummary, ...
    fullfile(resultFolder, ...
    "case_time_summary.csv"));

exportgraphics( ...
    fig, ...
    fullfile(resultFolder, ...
    "elapsed_time_vs_VB.png"), ...
    "Resolution",300);