paperRoot = fileparts(mfilename('fullpath'));
clear;
clc;
close all;

%% 1. Load data
resultFolder = ...
    fullfile(paperRoot, 'mill', 'results');

timeData = load(fullfile( ...
    resultFolder, ...
    "quality_aware_with_time.mat"));

locoData = load(fullfile( ...
    resultFolder, ...
    "time_model_results.mat"));

T = timeData.timeAwareTable;
locoPredictionTable = locoData.predictionTable;

assert(isequal( ...
    T.OriginalIndex, ...
    locoPredictionTable.OriginalIndex), ...
    "The data orders are inconsistent.");

%% 2. Basic variables
y = T.VB;
caseID = T.CaseID;
nSamples = height(T);

elapsedTime = T.ElapsedTime;
elapsedTimeSquared = elapsedTime.^2;

saturationRatio = ...
    T.smcDC_SaturationRatio;

XProcess = T{:,{'DOC','Feed','Material'}};

allVariableNames = ...
    string(T.Properties.VariableNames);

% The original 78 sensor features
sensorVariableNames = ...
    allVariableNames(8:85);

smcDCMask = startsWith( ...
    sensorVariableNames,"smcDC_");

otherSensorNames = ...
    sensorVariableNames(~smcDCMask);

XAllSensors = ...
    T{:,cellstr(sensorVariableNames)};

XOtherSensors = ...
    T{:,cellstr(otherSensorNames)};

%% 3. Time-augmented branches
XAllSensorsTime = [ ...
    XProcess, ...
    XAllSensors, ...
    elapsedTime, ...
    elapsedTimeSquared];

XQualityAwareTime = [ ...
    XProcess, ...
    XOtherSensors, ...
    elapsedTime, ...
    elapsedTimeSquared];

fprintf("AllSensorsTime dimension: %d\n", ...
    size(XAllSensorsTime,2));

fprintf("QualityAwareTime dimension: %d\n", ...
    size(XQualityAwareTime,2));

%% 4. LOCO result
predLOCO = ...
    locoPredictionTable.PredTimeGated;

locoResidual = predLOCO-y;

locoMAE = mean(abs(locoResidual));
locoRMSE = sqrt(mean(locoResidual.^2));

locoR2 = 1- ...
    sum(locoResidual.^2)/ ...
    sum((y-mean(y)).^2);

%% 5. Repeated random five-fold validation
numberOfRepeats = 20;
numberOfOuterFolds = 5;
numberOfInnerFolds = 5;

lambdaGrid = logspace(-4,4,17);
gateThresholdGrid = [0.01 0.10 0.50];

randomMAE = nan(numberOfRepeats,1);
randomRMSE = nan(numberOfRepeats,1);
randomR2 = nan(numberOfRepeats,1);
caseOverlapRate = nan(numberOfRepeats,1);

allRandomPredictions = ...
    nan(nSamples,numberOfRepeats);

selectedGateThresholds = ...
    nan(numberOfRepeats,numberOfOuterFolds);

for repeatIndex = 1:numberOfRepeats

    fprintf( ...
        "\nRandom validation repeat %d/%d\n", ...
        repeatIndex,numberOfRepeats);

    rng(20260716+repeatIndex,"twister");

    outerCV = cvpartition( ...
        nSamples,"KFold",numberOfOuterFolds);

    predAllBranch = nan(nSamples,1);
    predQualityBranch = nan(nSamples,1);
    predRandomGated = nan(nSamples,1);

    overlapCount = 0;

    for foldIndex = 1:numberOfOuterFolds

        fprintf("  Outer fold %d/%d\n", ...
            foldIndex,numberOfOuterFolds);

        outerTrainMask = ...
            training(outerCV,foldIndex);

        outerTestMask = ...
            test(outerCV,foldIndex);

        % Calculate case overlap
        trainingCases = ...
            unique(caseID(outerTrainMask));

        overlapCount = overlapCount + ...
            sum(ismember( ...
            caseID(outerTestMask), ...
            trainingCases));

        % Both lambdas and the gate threshold are selected from this
        % outer fold's training records only.
        [predAllBranch(outerTestMask), ...
            predQualityBranch(outerTestMask), ...
            predRandomGated(outerTestMask), ...
            selectedGateThresholds(repeatIndex,foldIndex)] = ...
            randomGatedRidgePrediction( ...
            XAllSensorsTime,XQualityAwareTime, ...
            saturationRatio,y,outerTrainMask,outerTestMask, ...
            lambdaGrid,numberOfInnerFolds,gateThresholdGrid);
    end

    allRandomPredictions(:,repeatIndex) = ...
        predRandomGated;

    residual = predRandomGated-y;

    randomMAE(repeatIndex) = ...
        mean(abs(residual));

    randomRMSE(repeatIndex) = ...
        sqrt(mean(residual.^2));

    randomR2(repeatIndex) = ...
        1-sum(residual.^2)/ ...
        sum((y-mean(y)).^2);

    caseOverlapRate(repeatIndex) = ...
        overlapCount/nSamples;
end

%% 6. Overall comparison
ValidationScheme = [ ...
    "Leave-One-Case-Out"; ...
    "Repeated Random 5-Fold"];

MAEMean = [ ...
    locoMAE; ...
    mean(randomMAE)];

MAEStandardDeviation = [ ...
    0; ...
    std(randomMAE)];

RMSEMean = [ ...
    locoRMSE; ...
    mean(randomRMSE)];

RMSEStandardDeviation = [ ...
    0; ...
    std(randomRMSE)];

R2Mean = [ ...
    locoR2; ...
    mean(randomR2)];

R2StandardDeviation = [ ...
    0; ...
    std(randomR2)];

MeanCaseOverlapRate = [ ...
    0; ...
    mean(caseOverlapRate)];

comparisonResults = table( ...
    ValidationScheme, ...
    MAEMean,MAEStandardDeviation, ...
    RMSEMean,RMSEStandardDeviation, ...
    R2Mean,R2StandardDeviation, ...
    MeanCaseOverlapRate);

fprintf("\n========== Validation comparison ==========\n");
disp(comparisonResults);

maeChangePercent = ...
    100*(mean(randomMAE)-locoMAE)/locoMAE;

rmseChangePercent = ...
    100*(mean(randomRMSE)-locoRMSE)/locoRMSE;

fprintf( ...
    "Random split MAE change relative to LOCO: %.2f%%\n", ...
    maeChangePercent);

fprintf( ...
    "Random split RMSE change relative to LOCO: %.2f%%\n", ...
    rmseChangePercent);

fprintf( ...
    "Mean test-record case-overlap rate: %.2f%%\n", ...
    100*mean(caseOverlapRate));

fprintf( ...
    "Negative change means random splitting gives a lower error.\n");

%% 7. Results from each repeat
repeatResults = table( ...
    (1:numberOfRepeats)', ...
    randomMAE,randomRMSE,randomR2, ...
    caseOverlapRate, ...
    'VariableNames', ...
    {'Repeat','MAE','RMSE','R2', ...
    'CaseOverlapRate'});

fprintf("\n========== Random-validation repeats ==========\n");
disp(repeatResults);

%% 8. Plot
fig = figure( ...
    "Color","w", ...
    "Position",[100 100 1100 520]);

metricMean = [ ...
    locoMAE,locoRMSE; ...
    mean(randomMAE),mean(randomRMSE)];

metricStandardDeviation = [ ...
    0,0; ...
    std(randomMAE),std(randomRMSE)];

barHandle = bar(metricMean,"grouped");
hold on;

numberOfGroups = size(metricMean,1);
numberOfBars = size(metricMean,2);
groupWidth = min(0.8,numberOfBars/(numberOfBars+1.5));

for barIndex = 1:numberOfBars

    xPosition = ...
        (1:numberOfGroups) - ...
        groupWidth/2 + ...
        (2*barIndex-1)* ...
        groupWidth/(2*numberOfBars);

    errorbar( ...
        xPosition, ...
        metricMean(:,barIndex), ...
        metricStandardDeviation(:,barIndex), ...
        "k", ...
        "LineStyle","none", ...
        "LineWidth",1.2);
end

hold off;
grid on;

set(gca, ...
    "XTick",1:2, ...
    "XTickLabel", ...
    ["Leave-One-Case-Out", ...
     "Repeated Random 5-Fold"]);

ylabel("Error");
legend(barHandle, ...
    ["MAE","RMSE"], ...
    "Location","northwest");

title("Random Split versus Leave-One-Case-Out");

%% 9. Save results
writetable( ...
    comparisonResults, ...
    fullfile(resultFolder, ...
    "random_vs_grouped_overall.csv"));

writetable( ...
    repeatResults, ...
    fullfile(resultFolder, ...
    "random_validation_repeats.csv"));

save( ...
    fullfile(resultFolder, ...
    "random_vs_grouped_results.mat"), ...
    "comparisonResults", ...
    "repeatResults", ...
    "allRandomPredictions", ...
    "predLOCO","selectedGateThresholds", ...
    "gateThresholdGrid");

exportgraphics( ...
    fig, ...
    fullfile(resultFolder, ...
    "random_vs_grouped_comparison.png"), ...
    "Resolution",300);

%% Local function: nested random gate and lambda selection
function [testPredictionAll,testPredictionQuality, ...
    testPredictionGated,bestGateThreshold] = ...
    randomGatedRidgePrediction( ...
    XAll,XQuality,qualityRatio,y,outerTrainMask,outerTestMask, ...
    lambdaGrid,numberOfInnerFolds,gateThresholdGrid)

outerTrainingIndex = find(outerTrainMask);
innerCV = cvpartition(numel(outerTrainingIndex), ...
    "KFold",numberOfInnerFolds);

[testPredictionAll,innerPredictionAll] = ...
    randomBranchPredictionAndOOF( ...
    XAll,y,outerTrainMask,outerTestMask,lambdaGrid,innerCV);

[testPredictionQuality,innerPredictionQuality] = ...
    randomBranchPredictionAndOOF( ...
    XQuality,y,outerTrainMask,outerTestMask,lambdaGrid,innerCV);

validationMAE = nan(numel(gateThresholdGrid),1);
for thresholdIndex = 1:numel(gateThresholdGrid)
    innerGatedPrediction = innerPredictionAll;
    switchMask = outerTrainMask & ...
        qualityRatio >= gateThresholdGrid(thresholdIndex);
    innerGatedPrediction(switchMask) = ...
        innerPredictionQuality(switchMask);
    validationMAE(thresholdIndex) = mean(abs( ...
        innerGatedPrediction(outerTrainMask)-y(outerTrainMask)));
end

minimumMAE = min(validationMAE);
candidateIndices = find(validationMAE <= minimumMAE + ...
    1e-12*max(1,abs(minimumMAE)));
[~,tieIndex] = max(gateThresholdGrid(candidateIndices));
bestIndex = candidateIndices(tieIndex);
bestGateThreshold = gateThresholdGrid(bestIndex);

testPredictionGated = testPredictionAll;
testSwitchMask = qualityRatio(outerTestMask) >= bestGateThreshold;
testPredictionGated(testSwitchMask) = ...
    testPredictionQuality(testSwitchMask);

end


%% Local function: random-fold branch selection and OOF predictions
function [testPrediction,bestInnerPrediction] = ...
    randomBranchPredictionAndOOF( ...
    X,y,outerTrainMask,outerTestMask,lambdaGrid,innerCV)

outerTrainingIndex = find(outerTrainMask);
validationMAE = nan(numel(lambdaGrid),1);
allInnerPredictions = nan(numel(y),numel(lambdaGrid));

for lambdaIndex = 1:numel(lambdaGrid)
    currentLambda = lambdaGrid(lambdaIndex);
    innerPrediction = nan(size(y));

    for innerFold = 1:innerCV.NumTestSets
        innerTrainingLocal = training(innerCV,innerFold);
        innerValidationLocal = test(innerCV,innerFold);
        innerTrainingIndex = outerTrainingIndex(innerTrainingLocal);
        innerValidationIndex = outerTrainingIndex(innerValidationLocal);

        innerPrediction(innerValidationIndex) = localFitRidge( ...
            X(innerTrainingIndex,:),y(innerTrainingIndex), ...
            X(innerValidationIndex,:),currentLambda);
    end

    allInnerPredictions(:,lambdaIndex) = innerPrediction;
    validationMAE(lambdaIndex) = mean(abs( ...
        y(outerTrainingIndex)-innerPrediction(outerTrainingIndex)));
end

[~,bestIndex] = min(validationMAE);
bestLambda = lambdaGrid(bestIndex);
bestInnerPrediction = allInnerPredictions(:,bestIndex);
testPrediction = localFitRidge(X(outerTrainMask,:),y(outerTrainMask), ...
    X(outerTestMask,:),bestLambda);

end

%% Local function: ridge regression
function prediction = localFitRidge( ...
    XTraining,yTraining,XTest,lambda)

featureMean = mean(XTraining,1);
featureStandardDeviation = std(XTraining,0,1);

validFeatureMask = ...
    featureStandardDeviation > 1e-12;

XTraining = XTraining(:,validFeatureMask);
XTest = XTest(:,validFeatureMask);

featureMean = ...
    featureMean(validFeatureMask);

featureStandardDeviation = ...
    featureStandardDeviation(validFeatureMask);

XTraining = ...
    (XTraining-featureMean)./ ...
    featureStandardDeviation;

XTest = ...
    (XTest-featureMean)./ ...
    featureStandardDeviation;

responseMean = mean(yTraining);
centeredResponse = yTraining-responseMean;

numberOfFeatures = size(XTraining,2);

coefficient = ...
    (XTraining'*XTraining + ...
    lambda*eye(numberOfFeatures)) \ ...
    (XTraining'*centeredResponse);

prediction = ...
    responseMean + XTest*coefficient;

end
