paperRoot = fileparts(mfilename('fullpath'));
clear;
clc;
close all;

%% 1. Paths
resultFolder = ...
    fullfile(paperRoot, 'mill', 'results');

timeData = load(fullfile( ...
    resultFolder, ...
    "quality_aware_with_time.mat"));

ridgeData = load(fullfile( ...
    resultFolder, ...
    "time_model_results.mat"));

T = timeData.timeAwareTable;
ridgePredictionTable = ridgeData.predictionTable;
assert(isfield(ridgeData,"thresholdSelectionTable"), ...
    "Training-only gate selections are missing. Rerun step15 first.");
thresholdSelectionTable = ridgeData.thresholdSelectionTable;

assert(isequal( ...
    T.OriginalIndex, ...
    ridgePredictionTable.OriginalIndex), ...
    "The data orders are inconsistent.");

%% 2. Basic variables
y = T.VB;
caseID = T.CaseID;
caseList = unique(caseID);

numberOfSamples = height(T);
numberOfCases = numel(caseList);

elapsedTime = T.ElapsedTime;
elapsedTimeSquared = elapsedTime.^2;
saturationRatio = T.smcDC_SaturationRatio;

allVariableNames = ...
    string(T.Properties.VariableNames);

sensorVariableNames = ...
    allVariableNames(8:85);

smcDCMask = startsWith( ...
    sensorVariableNames,"smcDC_");

otherSensorNames = ...
    sensorVariableNames(~smcDCMask);

XProcess = T{:,{'DOC','Feed','Material'}};

XAllSensors = ...
    T{:,cellstr(sensorVariableNames)};

XOtherSensors = ...
    T{:,cellstr(otherSensorNames)};

XAllSensorsTime = [ ...
    XProcess,XAllSensors, ...
    elapsedTime,elapsedTimeSquared];

XQualityAwareTime = [ ...
    XProcess,XOtherSensors, ...
    elapsedTime,elapsedTimeSquared];

fprintf("AllSensorsTime dimension: %d\n", ...
    size(XAllSensorsTime,2));

fprintf("QualityAwareTime dimension: %d\n", ...
    size(XQualityAwareTime,2));

%% 3. Small nested hyperparameter grids
% Columns: [number of learning cycles, minimum leaf size, learn rate]
% Learn rate is unused for bagged trees.
bagConfigurations = [ ...
    100,2,NaN; ...
    100,5,NaN; ...
    100,10,NaN];

boostConfigurations = [ ...
    100,2,0.03; ...
    100,2,0.10; ...
    100,5,0.03; ...
    100,5,0.10];

%% 4. Allocate predictions
predBagAll = nan(numberOfSamples,1);
predBagQuality = nan(numberOfSamples,1);
predBagGated = nan(numberOfSamples,1);

predBoostAll = nan(numberOfSamples,1);
predBoostQuality = nan(numberOfSamples,1);
predBoostGated = nan(numberOfSamples,1);

bestBagAll = nan(numberOfCases,1);
bestBagQuality = nan(numberOfCases,1);
bestBoostAll = nan(numberOfCases,1);
bestBoostQuality = nan(numberOfCases,1);

%% 5. Nested leave-one-case-out evaluation
for caseIndex = 1:numberOfCases

    testCase = caseList(caseIndex);

    testMask = caseID == testCase;
    trainMask = ~testMask;

    fprintf("\n========== Outer test Case %d ==========\n", ...
        testCase);

    fprintf("Bagged Trees: AllSensorsTime\n");

    [predBagAll(testMask),bestBagAll(caseIndex)] = ...
        groupedTreeEnsemblePrediction( ...
        XAllSensorsTime,y,caseID, ...
        trainMask,testMask, ...
        "Bag",bagConfigurations, ...
        20260716+1000*caseIndex);

    fprintf("Bagged Trees: QualityAwareTime\n");

    [predBagQuality(testMask),bestBagQuality(caseIndex)] = ...
        groupedTreeEnsemblePrediction( ...
        XQualityAwareTime,y,caseID, ...
        trainMask,testMask, ...
        "Bag",bagConfigurations, ...
        20261716+1000*caseIndex);

    fprintf("LSBoost: AllSensorsTime\n");

    [predBoostAll(testMask),bestBoostAll(caseIndex)] = ...
        groupedTreeEnsemblePrediction( ...
        XAllSensorsTime,y,caseID, ...
        trainMask,testMask, ...
        "LSBoost",boostConfigurations, ...
        20262716+1000*caseIndex);

    fprintf("LSBoost: QualityAwareTime\n");

    [predBoostQuality(testMask),bestBoostQuality(caseIndex)] = ...
        groupedTreeEnsemblePrediction( ...
        XQualityAwareTime,y,caseID, ...
        trainMask,testMask, ...
        "LSBoost",boostConfigurations, ...
        20263716+1000*caseIndex);

    thresholdRow = thresholdSelectionTable.TestCase == testCase;
    assert(sum(thresholdRow) == 1, ...
        "Missing or duplicated training-selected gate for Case %d.",testCase);
    currentGateThreshold = ...
        thresholdSelectionTable.TimeGateThreshold(thresholdRow);
    currentSwitchMask = testMask & ...
        saturationRatio >= currentGateThreshold;

    predBagGated(testMask) = predBagAll(testMask);
    predBagGated(currentSwitchMask) = predBagQuality(currentSwitchMask);
    predBoostGated(testMask) = predBoostAll(testMask);
    predBoostGated(currentSwitchMask) = predBoostQuality(currentSwitchMask);
end

%% 6. Proposed ridge reference
predRidgeGated = ...
    ridgePredictionTable.PredTimeGated;

%% 7. Overall evaluation
modelNames = [ ...
    "RidgeTimeGated"; ...
    "BaggedAllSensors"; ...
    "BaggedQualityAware"; ...
    "BaggedTimeGated"; ...
    "BoostAllSensors"; ...
    "BoostQualityAware"; ...
    "BoostTimeGated"];

predictionMatrix = [ ...
    predRidgeGated, ...
    predBagAll, ...
    predBagQuality, ...
    predBagGated, ...
    predBoostAll, ...
    predBoostQuality, ...
    predBoostGated];

numberOfModels = numel(modelNames);

MAE = nan(numberOfModels,1);
RMSE = nan(numberOfModels,1);
R2 = nan(numberOfModels,1);
P95AbsoluteError = nan(numberOfModels,1);
MaximumAbsoluteError = nan(numberOfModels,1);

for modelIndex = 1:numberOfModels

    residual = ...
        predictionMatrix(:,modelIndex)-y;

    absoluteError = abs(residual);

    MAE(modelIndex) = mean(absoluteError);
    RMSE(modelIndex) = sqrt(mean(residual.^2));

    R2(modelIndex) = 1- ...
        sum(residual.^2) / ...
        sum((y-mean(y)).^2);

    P95AbsoluteError(modelIndex) = ...
        prctile(absoluteError,95);

    MaximumAbsoluteError(modelIndex) = ...
        max(absoluteError);
end

MAEChangeFromRidge = MAE-MAE(1);

MAEChangePercentFromRidge = ...
    100*MAEChangeFromRidge/MAE(1);

overallResults = table( ...
    modelNames,MAE,RMSE,R2, ...
    P95AbsoluteError,MaximumAbsoluteError, ...
    MAEChangeFromRidge, ...
    MAEChangePercentFromRidge, ...
    'VariableNames', ...
    {'Model','MAE','RMSE','R2', ...
     'P95AbsoluteError','MaximumAbsoluteError', ...
     'MAEChangeFromRidge', ...
     'MAEChangePercentFromRidge'});

overallResults = sortrows( ...
    overallResults,"MAE","ascend");

fprintf("\n========== Tree ensemble baseline results ==========\n");
disp(overallResults);

%% 8. Case-level MAE
caseSampleCount = nan(numberOfCases,1);
caseMAE = nan(numberOfCases,numberOfModels);

for caseIndex = 1:numberOfCases

    mask = caseID == caseList(caseIndex);
    caseSampleCount(caseIndex) = sum(mask);

    for modelIndex = 1:numberOfModels
        caseMAE(caseIndex,modelIndex) = ...
            mean(abs( ...
            predictionMatrix(mask,modelIndex)-y(mask)));
    end
end

caseResultTable = table( ...
    caseList,caseSampleCount, ...
    'VariableNames', ...
    {'CaseID','SampleCount'});

for modelIndex = 1:numberOfModels
    caseResultTable.(char(modelNames(modelIndex))) = ...
        caseMAE(:,modelIndex);
end

%% 9. Hyperparameter selections
hyperparameterResults = table( ...
    caseList,bestBagAll,bestBagQuality, ...
    bestBoostAll,bestBoostQuality, ...
    thresholdSelectionTable.TimeGateThreshold, ...
    'VariableNames', ...
    {'TestCase','BestBagAllIndex', ...
     'BestBagQualityIndex', ...
     'BestBoostAllIndex', ...
     'BestBoostQualityIndex','TrainingSelectedGateThreshold'});

%% 10. Plot
fig = figure( ...
    "Color","w", ...
    "Position",[100 100 1350 600]);

metricMatrix = [MAE RMSE];

barHandle = bar( ...
    categorical(modelNames), ...
    metricMatrix,"grouped");

grid on;
ylabel("Error");
title("Nested LOCO Comparison of Ridge and Tree Ensembles");
legend(barHandle,["MAE","RMSE"], ...
    "Location","northwest");

currentAxis = gca;
currentAxis.TickLabelInterpreter = "none";

if ~isempty(currentAxis.Toolbar)
    currentAxis.Toolbar.Visible = "off";
end

disableDefaultInteractivity(currentAxis);
drawnow;

%% 11. Save
predictionTable = table( ...
    T.OriginalIndex,caseID,T.RunID,y, ...
    predRidgeGated,predBagAll, ...
    predBagQuality,predBagGated, ...
    predBoostAll,predBoostQuality, ...
    predBoostGated, ...
    'VariableNames', ...
    {'OriginalIndex','CaseID','RunID','ActualVB', ...
     'RidgeTimeGated','BaggedAllSensors', ...
     'BaggedQualityAware','BaggedTimeGated', ...
     'BoostAllSensors','BoostQualityAware', ...
     'BoostTimeGated'});

writetable( ...
    overallResults, ...
    fullfile(resultFolder, ...
    "tree_ensemble_overall.csv"));

writetable( ...
    caseResultTable, ...
    fullfile(resultFolder, ...
    "tree_ensemble_cases.csv"));

writetable( ...
    hyperparameterResults, ...
    fullfile(resultFolder, ...
    "tree_ensemble_hyperparameters.csv"));

writetable( ...
    predictionTable, ...
    fullfile(resultFolder, ...
    "tree_ensemble_predictions.csv"));

save( ...
    fullfile(resultFolder, ...
    "tree_ensemble_results.mat"), ...
    "overallResults","caseResultTable", ...
    "hyperparameterResults","predictionTable", ...
    "bagConfigurations","boostConfigurations", ...
    "thresholdSelectionTable");

exportgraphics( ...
    fig, ...
    fullfile(resultFolder, ...
    "tree_ensemble_comparison.png"), ...
    "Resolution",300);

fprintf("\nSaved tree-ensemble results to:\n%s\n", ...
    resultFolder);


%% Local function: nested grouped hyperparameter selection
function [testPrediction,bestConfigurationIndex] = ...
    groupedTreeEnsemblePrediction( ...
    X,y,groupID,outerTrainMask,outerTestMask, ...
    methodName,configurationMatrix,seedBase)

trainingCases = unique(groupID(outerTrainMask));
numberOfConfigurations = size(configurationMatrix,1);

validationMAE = nan(numberOfConfigurations,1);

for configurationIndex = 1:numberOfConfigurations

    validationPrediction = nan(size(y));

    for validationCaseIndex = 1:numel(trainingCases)

        validationCase = ...
            trainingCases(validationCaseIndex);

        innerValidationMask = ...
            outerTrainMask & ...
            groupID == validationCase;

        innerTrainingMask = ...
            outerTrainMask & ...
            groupID ~= validationCase;

        currentSeed = ...
            seedBase + ...
            100*configurationIndex + ...
            validationCaseIndex;

        validationPrediction(innerValidationMask) = ...
            fitTreeEnsembleAndPredict( ...
            X(innerTrainingMask,:), ...
            y(innerTrainingMask), ...
            X(innerValidationMask,:), ...
            methodName, ...
            configurationMatrix(configurationIndex,:), ...
            currentSeed);
    end

    validationMAE(configurationIndex) = ...
        mean(abs( ...
        y(outerTrainMask)- ...
        validationPrediction(outerTrainMask)));
end

[~,bestConfigurationIndex] = min(validationMAE);

testPrediction = fitTreeEnsembleAndPredict( ...
    X(outerTrainMask,:), ...
    y(outerTrainMask), ...
    X(outerTestMask,:), ...
    methodName, ...
    configurationMatrix(bestConfigurationIndex,:), ...
    seedBase+9999);

end


%% Local function: fit Bagged Trees or LSBoost
function prediction = fitTreeEnsembleAndPredict( ...
    XTraining,yTraining,XTest, ...
    methodName,configuration,seedValue)

numberOfCycles = configuration(1);
minimumLeafSize = configuration(2);
learnRate = configuration(3);

rng(seedValue,"twister");

if methodName == "Bag"

    numberOfVariablesToSample = max( ...
        1,round(sqrt(size(XTraining,2))));

    treeTemplate = templateTree( ...
        "MinLeafSize",minimumLeafSize, ...
        "NumVariablesToSample", ...
        numberOfVariablesToSample);

    model = fitrensemble( ...
        XTraining,yTraining, ...
        "Method","Bag", ...
        "NumLearningCycles",numberOfCycles, ...
        "Learners",treeTemplate);

elseif methodName == "LSBoost"

    treeTemplate = templateTree( ...
        "MinLeafSize",minimumLeafSize);

    model = fitrensemble( ...
        XTraining,yTraining, ...
        "Method","LSBoost", ...
        "NumLearningCycles",numberOfCycles, ...
        "LearnRate",learnRate, ...
        "Learners",treeTemplate);

else
    error("Unsupported ensemble method: %s",methodName);
end

prediction = predict(model,XTest);

end
