paperRoot = fileparts(mfilename('fullpath'));
clear;
clc;
close all;

%% 1. 路径和数据
filePath = ...
    fullfile(paperRoot, 'mill', 'mill.mat');

resultFolder = ...
    fullfile(paperRoot, 'mill', 'results');

raw = load(filePath);
mill = raw.mill;

featureData = load( ...
    fullfile(resultFolder, ...
    "run_level_features.mat"));

featureTable = featureData.featureTable;

signalNames = [ ...
    "smcAC", ...
    "smcDC", ...
    "vib_table", ...
    "vib_spindle", ...
    "AE_table", ...
    "AE_spindle"];

validIndices = featureTable.OriginalIndex;
nValid = numel(validIndices);
nSignals = numel(signalNames);

%% 2. 计算每个传感器在全部有效记录中的全局上下限
globalMinimum = inf(1,nSignals);
globalMaximum = -inf(1,nSignals);

for s = 1:nSignals

    for row = 1:nValid

        sourceIndex = validIndices(row);

        x = double( ...
            mill(sourceIndex).(signalNames(s)));

        x = x(:);

        n = numel(x);

        startIndex = floor(0.25*n)+1;
        endIndex = floor(0.75*n);

        xCentral = x(startIndex:endIndex);

        globalMinimum(s) = min( ...
            globalMinimum(s), ...
            min(xCentral));

        globalMaximum(s) = max( ...
            globalMaximum(s), ...
            max(xCentral));
    end
end

globalRangeTable = table( ...
    signalNames', ...
    globalMinimum', ...
    globalMaximum', ...
    'VariableNames', ...
    {'Sensor','GlobalMinimum','GlobalMaximum'});

fprintf("========== 六路信号的中心区域全局范围 ==========\n");
disp(globalRangeTable);

%% 3. 初始化审计结果
nRows = nValid*nSignals;

OriginalIndex = nan(nRows,1);
CaseID = nan(nRows,1);
RunID = nan(nRows,1);
VB = nan(nRows,1);
Sensor = strings(nRows,1);

SignalMean = nan(nRows,1);
SignalStd = nan(nRows,1);
SignalMAD = nan(nRows,1);
ModeValue = nan(nRows,1);
ModeRatio = nan(nRows,1);
UpperRailRatio = nan(nRows,1);
LowerRailRatio = nan(nRows,1);

resultRow = 0;

%% 4. 扫描每条记录的六路信号
for row = 1:nValid

    sourceIndex = validIndices(row);

    for s = 1:nSignals

        resultRow = resultRow+1;

        x = double( ...
            mill(sourceIndex).(signalNames(s)));

        x = x(:);

        n = numel(x);

        startIndex = floor(0.25*n)+1;
        endIndex = floor(0.75*n);

        xCentral = x(startIndex:endIndex);

        signalRange = ...
            globalMaximum(s)-globalMinimum(s);

        tolerance = max( ...
            1e-12, ...
            1e-8*max(signalRange,1));

        upperMask = ...
            abs(xCentral-globalMaximum(s)) ...
            <= tolerance;

        lowerMask = ...
            abs(xCentral-globalMinimum(s)) ...
            <= tolerance;

        [currentMode,modeFrequency] = ...
            mode(xCentral);

        OriginalIndex(resultRow) = sourceIndex;
        CaseID(resultRow) = mill(sourceIndex).case;
        RunID(resultRow) = mill(sourceIndex).run;
        VB(resultRow) = mill(sourceIndex).VB;
        Sensor(resultRow) = signalNames(s);

        SignalMean(resultRow) = mean(xCentral);
        SignalStd(resultRow) = std(xCentral);
        SignalMAD(resultRow) = mad(xCentral,1);

        ModeValue(resultRow) = currentMode;
        ModeRatio(resultRow) = ...
            modeFrequency/numel(xCentral);

        UpperRailRatio(resultRow) = ...
            mean(upperMask);

        LowerRailRatio(resultRow) = ...
            mean(lowerMask);
    end
end

%% 5. 建立审计表
RailRatio = max( ...
    UpperRailRatio, ...
    LowerRailRatio);

saturationTable = table( ...
    OriginalIndex,CaseID,RunID,VB,Sensor, ...
    SignalMean,SignalStd,SignalMAD, ...
    ModeValue,ModeRatio, ...
    UpperRailRatio,LowerRailRatio,RailRatio);

saturationTable = sortrows( ...
    saturationTable, ...
    "RailRatio", ...
    "descend");

fprintf("\n========== 饱和比例最高的20个通道 ==========\n");

disp(saturationTable(1:20,{ ...
    'OriginalIndex', ...
    'CaseID', ...
    'RunID', ...
    'VB', ...
    'Sensor', ...
    'ModeValue', ...
    'ModeRatio', ...
    'UpperRailRatio', ...
    'LowerRailRatio', ...
    'RailRatio'}));

%% 6. 各传感器的饱和记录统计
CountAbove1Percent = nan(nSignals,1);
CountAbove10Percent = nan(nSignals,1);
CountAbove50Percent = nan(nSignals,1);
MaximumRailRatio = nan(nSignals,1);

for s = 1:nSignals

    mask = Sensor == signalNames(s);

    CountAbove1Percent(s) = ...
        sum(RailRatio(mask) >= 0.01);

    CountAbove10Percent(s) = ...
        sum(RailRatio(mask) >= 0.10);

    CountAbove50Percent(s) = ...
        sum(RailRatio(mask) >= 0.50);

    MaximumRailRatio(s) = ...
        max(RailRatio(mask));
end

sensorSaturationSummary = table( ...
    signalNames', ...
    CountAbove1Percent, ...
    CountAbove10Percent, ...
    CountAbove50Percent, ...
    MaximumRailRatio, ...
    'VariableNames', ...
    {'Sensor','Above1Percent', ...
     'Above10Percent','Above50Percent', ...
     'MaximumRailRatio'});

fprintf("\n========== 各传感器饱和情况汇总 ==========\n");
disp(sensorSaturationSummary);

%% 7. 单独检查smcDC接近10的比例
smcDCRows = saturationTable.Sensor == "smcDC";

smcDCDetails = saturationTable( ...
    smcDCRows,:);

smcDCDetails = sortrows( ...
    smcDCDetails, ...
    "UpperRailRatio", ...
    "descend");

fprintf("\n========== smcDC上限占比最高的记录 ==========\n");

disp(smcDCDetails(1:min(15,height(smcDCDetails)),{ ...
    'OriginalIndex', ...
    'CaseID', ...
    'RunID', ...
    'VB', ...
    'SignalMean', ...
    'SignalStd', ...
    'SignalMAD', ...
    'ModeValue', ...
    'ModeRatio', ...
    'UpperRailRatio'}));

%% 8. 保存
writetable( ...
    saturationTable, ...
    fullfile(resultFolder, ...
    "sensor_saturation_audit.csv"));

writetable( ...
    sensorSaturationSummary, ...
    fullfile(resultFolder, ...
    "sensor_saturation_summary.csv"));

writetable( ...
    globalRangeTable, ...
    fullfile(resultFolder, ...
    "sensor_global_ranges.csv"));

save( ...
    fullfile(resultFolder, ...
    "sensor_saturation_results.mat"), ...
    "saturationTable", ...
    "sensorSaturationSummary", ...
    "globalRangeTable");