paperRoot = fileparts(mfilename('fullpath'));
clear;
clc;
close all;

%% 1. Result folder
resultFolder = ...
    fullfile(paperRoot, 'mill', 'results');

%% 2. Read result files
baseline = readtable(fullfile( ...
    resultFolder, ...
    "baseline_overall_results.csv"));

gated = readtable(fullfile( ...
    resultFolder, ...
    "gated_overall_results.csv"));

svrResults = readtable(fullfile( ...
    resultFolder, ...
    "svr_overall_results.csv"));

timeResults = readtable(fullfile( ...
    resultFolder, ...
    "time_model_overall.csv"));

statistical = readtable(fullfile( ...
    resultFolder, ...
    "statistical_overall_results.csv"));

randomResults = readtable(fullfile( ...
    resultFolder, ...
    "random_vs_grouped_overall.csv"));

treeResults = readtable(fullfile( ...
    resultFolder, ...
    "tree_ensemble_overall.csv"));

%% 3. Convert text columns to strings
baseline.Model = string(baseline.Model);
gated.Strategy = string(gated.Strategy);
svrResults.Model = string(svrResults.Model);
timeResults.Model = string(timeResults.Model);
treeResults.Model = string(treeResults.Model);

randomResults.ValidationScheme = ...
    string(randomResults.ValidationScheme);

%% 4. Assemble final model comparison table
Model = [ ...
    "Training mean"; ...
    "Process parameters only"; ...
    "Sensor ridge"; ...
    "Process + sensor ridge"; ...
    "Quality-aware ridge"; ...
    "Quality-gated ridge"; ...
    "All-sensor SVR"; ...
    "Quality-aware SVR"; ...
    "Quality-aware bagged trees"; ...
    "Quality-aware LSBoost"; ...
    "Process + elapsed time"; ...
    "All sensors + elapsed time"; ...
    "Quality-aware + elapsed time"; ...
    "Time- and quality-gated ridge"];

ModelRole = [ ...
    "Naive baseline"; ...
    "Process baseline"; ...
    "Sensor baseline"; ...
    "Conventional model"; ...
    "Quality ablation"; ...
    "Quality-gating model"; ...
    "Nonlinear comparison"; ...
    "Nonlinear comparison"; ...
    "Nonlinear comparison"; ...
    "Nonlinear comparison"; ...
    "Time ablation"; ...
    "Time ablation"; ...
    "Time ablation"; ...
    "Proposed model"];

MAE = [ ...
    baseline.MAE( ...
    baseline.Model=="Training mean"); ...
    
    baseline.MAE( ...
    baseline.Model=="Process only"); ...
    
    baseline.MAE( ...
    baseline.Model=="Sensor ridge"); ...
    
    baseline.MAE( ...
    baseline.Model=="Process + sensor ridge"); ...
    
    gated.MAE( ...
    gated.Strategy=="QualityAware"); ...
    
    timeResults.MAE( ...
    timeResults.Model=="RidgeGated"); ...
    
    svrResults.MAE( ...
    svrResults.Model=="SVRAllSensors"); ...
    
    svrResults.MAE( ...
    svrResults.Model=="SVRQualityAware"); ...

    treeResults.MAE( ...
    treeResults.Model=="BaggedQualityAware"); ...

    treeResults.MAE( ...
    treeResults.Model=="BoostQualityAware"); ...
    
    timeResults.MAE( ...
    timeResults.Model=="TimeOnly"); ...
    
    timeResults.MAE( ...
    timeResults.Model=="AllSensorsTime"); ...
    
    timeResults.MAE( ...
    timeResults.Model=="QualityAwareTime"); ...
    
    timeResults.MAE( ...
    timeResults.Model=="TimeGated")];

RMSE = [ ...
    baseline.RMSE( ...
    baseline.Model=="Training mean"); ...
    
    baseline.RMSE( ...
    baseline.Model=="Process only"); ...
    
    baseline.RMSE( ...
    baseline.Model=="Sensor ridge"); ...
    
    baseline.RMSE( ...
    baseline.Model=="Process + sensor ridge"); ...
    
    gated.RMSE( ...
    gated.Strategy=="QualityAware"); ...
    
    timeResults.RMSE( ...
    timeResults.Model=="RidgeGated"); ...
    
    svrResults.RMSE( ...
    svrResults.Model=="SVRAllSensors"); ...
    
    svrResults.RMSE( ...
    svrResults.Model=="SVRQualityAware"); ...

    treeResults.RMSE( ...
    treeResults.Model=="BaggedQualityAware"); ...

    treeResults.RMSE( ...
    treeResults.Model=="BoostQualityAware"); ...
    
    timeResults.RMSE( ...
    timeResults.Model=="TimeOnly"); ...
    
    timeResults.RMSE( ...
    timeResults.Model=="AllSensorsTime"); ...
    
    timeResults.RMSE( ...
    timeResults.Model=="QualityAwareTime"); ...
    
    timeResults.RMSE( ...
    timeResults.Model=="TimeGated")];

R2 = [ ...
    baseline.R2( ...
    baseline.Model=="Training mean"); ...
    
    baseline.R2( ...
    baseline.Model=="Process only"); ...
    
    baseline.R2( ...
    baseline.Model=="Sensor ridge"); ...
    
    baseline.R2( ...
    baseline.Model=="Process + sensor ridge"); ...
    
    gated.R2( ...
    gated.Strategy=="QualityAware"); ...
    
    timeResults.R2( ...
    timeResults.Model=="RidgeGated"); ...
    
    svrResults.R2( ...
    svrResults.Model=="SVRAllSensors"); ...
    
    svrResults.R2( ...
    svrResults.Model=="SVRQualityAware"); ...

    treeResults.R2( ...
    treeResults.Model=="BaggedQualityAware"); ...

    treeResults.R2( ...
    treeResults.Model=="BoostQualityAware"); ...
    
    timeResults.R2( ...
    timeResults.Model=="TimeOnly"); ...
    
    timeResults.R2( ...
    timeResults.Model=="AllSensorsTime"); ...
    
    timeResults.R2( ...
    timeResults.Model=="QualityAwareTime"); ...
    
    timeResults.R2( ...
    timeResults.Model=="TimeGated")];

IsProposedModel = ...
    Model == "Time- and quality-gated ridge";

paperModelTable = table( ...
    Model,ModelRole, ...
    MAE,RMSE,R2, ...
    IsProposedModel);

%% 5. Sort models by MAE
% Ascending order: best model is first
paperModelTable = sortrows( ...
    paperModelTable, ...
    "MAE","ascend");

fprintf("========== Final model comparison ==========\n");
disp(paperModelTable);

%% 6. Main improvement values
conventionalMAE = ...
    baseline.MAE( ...
    baseline.Model=="Process + sensor ridge");

conventionalRMSE = ...
    baseline.RMSE( ...
    baseline.Model=="Process + sensor ridge");

conventionalR2 = ...
    baseline.R2( ...
    baseline.Model=="Process + sensor ridge");

proposedMAE = ...
    timeResults.MAE( ...
    timeResults.Model=="TimeGated");

proposedRMSE = ...
    timeResults.RMSE( ...
    timeResults.Model=="TimeGated");

proposedR2 = ...
    timeResults.R2( ...
    timeResults.Model=="TimeGated");

MAEImprovementVsConventional = ...
    100*(conventionalMAE-proposedMAE) / ...
    conventionalMAE;

RMSEImprovementVsConventional = ...
    100*(conventionalRMSE-proposedRMSE) / ...
    conventionalRMSE;

R2AbsoluteImprovement = ...
    proposedR2-conventionalR2;

fprintf("\n========== Main paper findings ==========\n");

fprintf( ...
    "MAE improvement versus conventional model: %.2f%%\n", ...
    MAEImprovementVsConventional);

fprintf( ...
    "RMSE improvement versus conventional model: %.2f%%\n", ...
    RMSEImprovementVsConventional);

fprintf( ...
    "Absolute R2 improvement: %.4f\n", ...
    R2AbsoluteImprovement);

fprintf( ...
    "TimeGated versus RidgeGated Wilcoxon p: %.6f\n", ...
    statistical.WilcoxonP(1));

fprintf( ...
    "Random split case-overlap rate: %.2f%%\n", ...
    100*randomResults.MeanCaseOverlapRate(2));

fprintf( ...
    "Random split MAE: %.6f\n", ...
    randomResults.MAEMean(2));

fprintf( ...
    "LOCO MAE: %.6f\n", ...
    randomResults.MAEMean(1));

%% 7. Key findings table
Finding = [ ...
    "Proposed model MAE"; ...
    "Proposed model RMSE"; ...
    "Proposed model R2"; ...
    "MAE improvement vs conventional"; ...
    "RMSE improvement vs conventional"; ...
    "R2 absolute improvement"; ...
    "Paired Wilcoxon p-value"; ...
    "Bootstrap improvement probability"; ...
    "Random-split case overlap"; ...
    "Random-split MAE reduction vs LOCO"];

Value = [ ...
    proposedMAE; ...
    proposedRMSE; ...
    proposedR2; ...
    MAEImprovementVsConventional; ...
    RMSEImprovementVsConventional; ...
    R2AbsoluteImprovement; ...
    statistical.WilcoxonP(1); ...
    statistical.BootstrapImprovementProbability(1); ...
    100*randomResults.MeanCaseOverlapRate(2); ...
    100*(randomResults.MAEMean(1)- ...
    randomResults.MAEMean(2))/ ...
    randomResults.MAEMean(1)];

Unit = [ ...
    "VB"; ...
    "VB"; ...
    "dimensionless"; ...
    "%"; ...
    "%"; ...
    "dimensionless"; ...
    "p-value"; ...
    "probability"; ...
    "%"; ...
    "%"];

paperFindingTable = table( ...
    Finding,Value,Unit);

fprintf("\n========== Paper key findings ==========\n");
disp(paperFindingTable);

%% 8. Prepare plotting positions
numberOfModels = height(paperModelTable);

% Numerical positions preserve the sorted table order
yPosition = (1:numberOfModels)';

normalColor = [ ...
    0.20,0.55,0.80];

proposedColor = [ ...
    0.90,0.35,0.12];

barColors = repmat( ...
    normalColor, ...
    numberOfModels,1);

barColors( ...
    paperModelTable.IsProposedModel,:) = ...
    proposedColor;

%% 9. Create corrected paper figure
fig = figure( ...
    "Color","w", ...
    "Position",[80 80 1600 760]);

layout = tiledlayout( ...
    1,2, ...
    "TileSpacing","compact", ...
    "Padding","compact");

title(layout, ...
    "Performance Comparison under Leave-One-Case-Out Validation", ...
    "FontWeight","bold");

%% 9.1 MAE subplot
nexttile;

maeBar = barh( ...
    yPosition, ...
    paperModelTable.MAE, ...
    "FaceColor","flat");

maeBar.CData = barColors;

grid on;
box on;

yticks(yPosition);
yticklabels(paperModelTable.Model);

ylim([0.5,numberOfModels+0.5]);

% Best model is displayed at the top
set(gca,"YDir","reverse");

xlabel("Mean Absolute Error (MAE)");
title("Model Comparison by MAE");

maeAxis = gca;
maeAxis.TickLabelInterpreter = "none";
maeAxis.FontSize = 10;

% Add metric values
for modelIndex = 1:numberOfModels

    text( ...
        paperModelTable.MAE(modelIndex)+0.003, ...
        yPosition(modelIndex), ...
        sprintf("%.3f", ...
        paperModelTable.MAE(modelIndex)), ...
        "VerticalAlignment","middle", ...
        "FontSize",9);
end

xlim([0, ...
    max(paperModelTable.MAE)*1.20]);

%% 9.2 R2 subplot
nexttile;

r2Bar = barh( ...
    yPosition, ...
    paperModelTable.R2, ...
    "FaceColor","flat");

r2Bar.CData = barColors;

hold on;
xline(0,"k--","LineWidth",1);
hold off;

grid on;
box on;

yticks(yPosition);
yticklabels(paperModelTable.Model);

ylim([0.5,numberOfModels+0.5]);

set(gca,"YDir","reverse");

xlabel("Coefficient of Determination (R^2)");
title("Model Comparison by R^2");

r2Axis = gca;
r2Axis.TickLabelInterpreter = "none";
r2Axis.FontSize = 10;

% Add metric values
for modelIndex = 1:numberOfModels

    currentR2 = ...
        paperModelTable.R2(modelIndex);

    if currentR2 >= 0
        textPosition = currentR2+0.012;
        horizontalAlignment = "left";
    else
        textPosition = currentR2-0.012;
        horizontalAlignment = "right";
    end

    text( ...
        textPosition, ...
        yPosition(modelIndex), ...
        sprintf("%.3f",currentR2), ...
        "VerticalAlignment","middle", ...
        "HorizontalAlignment", ...
        horizontalAlignment, ...
        "FontSize",9);
end

xlim([ ...
    min(paperModelTable.R2)-0.08, ...
    max(paperModelTable.R2)+0.10]);

%% 10. Add color explanation
annotation( ...
    fig,"textbox", ...
    [0.38 0.008 0.24 0.03], ...
    "String","Orange bar: proposed model", ...
    "EdgeColor","none", ...
    "HorizontalAlignment","center", ...
    "FontSize",10, ...
    "Color",proposedColor);

%% 11. Save results
writetable( ...
    paperModelTable, ...
    fullfile(resultFolder, ...
    "paper_model_comparison.csv"));

writetable( ...
    paperFindingTable, ...
    fullfile(resultFolder, ...
    "paper_key_findings.csv"));
%% Hide axes toolbars before export
if ~isempty(maeAxis.Toolbar)
    maeAxis.Toolbar.Visible = "off";
end

if ~isempty(r2Axis.Toolbar)
    r2Axis.Toolbar.Visible = "off";
end

disableDefaultInteractivity(maeAxis);
disableDefaultInteractivity(r2Axis);

drawnow;
exportgraphics( ...
    fig, ...
    fullfile(resultFolder, ...
    "paper_model_comparison_corrected.png"), ...
    "Resolution",300);

fprintf("\nCorrected figure saved to:\n%s\n", ...
    fullfile(resultFolder, ...
    "paper_model_comparison_corrected.png"));
