paperRoot = fileparts(mfilename('fullpath'));
clear;
clc;
close all;

%% 1. 读取结果
resultFolder = ...
    fullfile(paperRoot, 'mill', 'results');

strategyData = load( ...
    fullfile(resultFolder, ...
    "quality_strategy_results.mat"));

qualityData = load( ...
    fullfile(resultFolder, ...
    "quality_aware_features.mat"));

predictionTable = ...
    strategyData.predictionTable;

qualityTable = ...
    qualityData.qualityAwareTable;

%% 2. 检查数据是否对齐
assert( ...
    isequal( ...
    predictionTable.OriginalIndex, ...
    qualityTable.OriginalIndex), ...
    "两个表的OriginalIndex顺序不一致");

actualVB = predictionTable.ActualVB;
caseID = predictionTable.CaseID;
runID = predictionTable.RunID;
originalIndex = predictionTable.OriginalIndex;

predAll = predictionTable.PredAllSensors;
predQuality = predictionTable.PredQualityAware;

saturationRatio = ...
    qualityTable.smcDC_SaturationRatio;

%% 3. 建立三个门控阈值
thresholds = [0.01 0.10 0.50];

predGated1 = predAll;
predGated10 = predAll;
predGated50 = predAll;

mask1 = saturationRatio >= thresholds(1);
mask10 = saturationRatio >= thresholds(2);
mask50 = saturationRatio >= thresholds(3);

predGated1(mask1) = predQuality(mask1);
predGated10(mask10) = predQuality(mask10);
predGated50(mask50) = predQuality(mask50);

fprintf("========== 门控样本数量 ==========\n");
fprintf("饱和比例 >= 1%%：%d\n",sum(mask1));
fprintf("饱和比例 >= 10%%：%d\n",sum(mask10));
fprintf("饱和比例 >= 50%%：%d\n",sum(mask50));

%% 4. 汇总预测
modelNames = [ ...
    "AllSensors", ...
    "QualityAware", ...
    "Gated1Percent", ...
    "Gated10Percent", ...
    "Gated50Percent"];

predictionMatrix = [ ...
    predAll, ...
    predQuality, ...
    predGated1, ...
    predGated10, ...
    predGated50];

nModels = numel(modelNames);

%% 5. 总体指标
MAE = nan(nModels,1);
RMSE = nan(nModels,1);
R2 = nan(nModels,1);
MaximumAbsoluteError = nan(nModels,1);
P95AbsoluteError = nan(nModels,1);

for m = 1:nModels

    residual = ...
        predictionMatrix(:,m)-actualVB;

    absoluteError = abs(residual);

    MAE(m) = mean(absoluteError);
    RMSE(m) = sqrt(mean(residual.^2));

    R2(m) = 1- ...
        sum(residual.^2)/ ...
        sum((actualVB-mean(actualVB)).^2);

    MaximumAbsoluteError(m) = ...
        max(absoluteError);

    P95AbsoluteError(m) = ...
        prctile(absoluteError,95);
end

overallResults = table( ...
    modelNames',MAE,RMSE,R2, ...
    P95AbsoluteError, ...
    MaximumAbsoluteError, ...
    'VariableNames', ...
    {'Strategy','MAE','RMSE','R2', ...
     'P95AbsoluteError', ...
     'MaximumAbsoluteError'});

fprintf("\n========== 质量门控总体结果 ==========\n");
disp(overallResults);

%% 6. 每个案例的MAE
caseList = unique(caseID);
caseMAE = nan(numel(caseList),nModels);
caseSampleCount = nan(numel(caseList),1);

for k = 1:numel(caseList)

    mask = caseID == caseList(k);

    caseSampleCount(k) = sum(mask);

    for m = 1:nModels
        caseMAE(k,m) = mean( ...
            abs(predictionMatrix(mask,m) - ...
            actualVB(mask)));
    end
end

caseResults = table( ...
    caseList, ...
    caseSampleCount, ...
    caseMAE(:,1), ...
    caseMAE(:,2), ...
    caseMAE(:,3), ...
    caseMAE(:,4), ...
    caseMAE(:,5), ...
    'VariableNames', ...
    {'CaseID','SampleCount', ...
     'AllSensorsMAE', ...
     'QualityAwareMAE', ...
     'Gated1MAE', ...
     'Gated10MAE', ...
     'Gated50MAE'});

fprintf("\n========== 每个案例的门控结果 ==========\n");
disp(caseResults);

%% 7. 不同磨损区间
wearGroupNames = [ ...
    "VB < 0.2", ...
    "0.2 <= VB < 0.4", ...
    "VB >= 0.4"];

wearMasks = { ...
    actualVB < 0.2, ...
    actualVB >= 0.2 & actualVB < 0.4, ...
    actualVB >= 0.4};

nWearGroups = numel(wearGroupNames);
nResultRows = nModels*nWearGroups;

Strategy = strings(nResultRows,1);
WearGroup = strings(nResultRows,1);
SampleCount = nan(nResultRows,1);
GroupMAE = nan(nResultRows,1);
GroupRMSE = nan(nResultRows,1);
MeanResidual = nan(nResultRows,1);

rowCounter = 0;

for m = 1:nModels

    for g = 1:nWearGroups

        rowCounter = rowCounter+1;

        mask = wearMasks{g};

        residual = ...
            predictionMatrix(mask,m)- ...
            actualVB(mask);

        Strategy(rowCounter) = modelNames(m);
        WearGroup(rowCounter) = ...
            wearGroupNames(g);

        SampleCount(rowCounter) = sum(mask);
        GroupMAE(rowCounter) = ...
            mean(abs(residual));

        GroupRMSE(rowCounter) = ...
            sqrt(mean(residual.^2));

        MeanResidual(rowCounter) = ...
            mean(residual);
    end
end

wearResults = table( ...
    Strategy,WearGroup,SampleCount, ...
    GroupMAE,GroupRMSE,MeanResidual);

fprintf("\n========== 不同磨损区间的门控结果 ==========\n");
disp(wearResults);

%% 8. 检查OriginalIndex 109
targetMask = originalIndex == 109;

targetResults = table( ...
    originalIndex(targetMask), ...
    actualVB(targetMask), ...
    saturationRatio(targetMask), ...
    predAll(targetMask), ...
    predQuality(targetMask), ...
    predGated1(targetMask), ...
    predGated10(targetMask), ...
    predGated50(targetMask), ...
    'VariableNames', ...
    {'OriginalIndex','ActualVB', ...
     'SaturationRatio','AllSensors', ...
     'QualityAware','Gated1', ...
     'Gated10','Gated50'});

fprintf("\n========== OriginalIndex 109门控结果 ==========\n");
disp(targetResults);

%% 9. 绘制总体指标
fig1 = figure( ...
    "Color","w", ...
    "Position",[100 100 1250 600]);

tiledlayout(1,2, ...
    "TileSpacing","compact", ...
    "Padding","compact");

nexttile;

bar(categorical(modelNames),MAE);
grid on;
ylabel("MAE");
title("Mean Absolute Error");

nexttile;

bar(categorical(modelNames),RMSE);
grid on;
ylabel("RMSE");
title("Root Mean Squared Error");

sgtitle("Quality-Gated Prediction Comparison");

%% 10. 绘制案例MAE
fig2 = figure( ...
    "Color","w", ...
    "Position",[100 100 1500 650]);

bar(caseList,caseMAE,"grouped");

grid on;
xlabel("Held-out case");
ylabel("MAE");
title("Case-Level Performance of Quality-Gated Prediction");
legend(modelNames,"Location","northwest");

%% 11. 保存
gatedPredictionTable = table( ...
    originalIndex,caseID,runID, ...
    actualVB,saturationRatio, ...
    predAll,predQuality, ...
    predGated1,predGated10,predGated50, ...
    'VariableNames', ...
    {'OriginalIndex','CaseID','RunID', ...
     'ActualVB','SaturationRatio', ...
     'PredAllSensors','PredQualityAware', ...
     'PredGated1','PredGated10','PredGated50'});

writetable( ...
    overallResults, ...
    fullfile(resultFolder, ...
    "gated_overall_results.csv"));

writetable( ...
    caseResults, ...
    fullfile(resultFolder, ...
    "gated_case_results.csv"));

writetable( ...
    wearResults, ...
    fullfile(resultFolder, ...
    "gated_wear_results.csv"));

writetable( ...
    gatedPredictionTable, ...
    fullfile(resultFolder, ...
    "gated_predictions.csv"));

save( ...
    fullfile(resultFolder, ...
    "gated_results.mat"), ...
    "overallResults","caseResults", ...
    "wearResults","gatedPredictionTable");

exportgraphics( ...
    fig1, ...
    fullfile(resultFolder, ...
    "gated_overall_metrics.png"), ...
    "Resolution",300);

exportgraphics( ...
    fig2, ...
    fullfile(resultFolder, ...
    "gated_case_MAE.png"), ...
    "Resolution",300);