paperRoot = fileparts(mfilename('fullpath'));
clear;
clc;
close all;

%% 1. Read predictions
resultFolder = ...
    fullfile(paperRoot, 'mill', 'results');

P = readtable(fullfile( ...
    resultFolder, ...
    "time_model_predictions.csv"));

caseID = P.CaseID;
actualVB = P.ActualVB;

predRidgeGated = P.PredRidgeGated;
predTimeGated = P.PredTimeGated;

caseList = unique(caseID);
numberOfCases = numel(caseList);

%% 2. Case-level errors
ridgeCaseMAE = nan(numberOfCases,1);
timeCaseMAE = nan(numberOfCases,1);

sampleCount = nan(numberOfCases,1);
ridgeErrorSum = nan(numberOfCases,1);
timeErrorSum = nan(numberOfCases,1);

for caseIndex = 1:numberOfCases

    mask = caseID == caseList(caseIndex);

    ridgeAbsoluteError = abs( ...
        predRidgeGated(mask)-actualVB(mask));

    timeAbsoluteError = abs( ...
        predTimeGated(mask)-actualVB(mask));

    sampleCount(caseIndex) = sum(mask);

    ridgeErrorSum(caseIndex) = ...
        sum(ridgeAbsoluteError);

    timeErrorSum(caseIndex) = ...
        sum(timeAbsoluteError);

    ridgeCaseMAE(caseIndex) = ...
        mean(ridgeAbsoluteError);

    timeCaseMAE(caseIndex) = ...
        mean(timeAbsoluteError);
end

caseDifference = ...
    timeCaseMAE-ridgeCaseMAE;

improvedCases = sum(caseDifference < 0);
worsenedCases = sum(caseDifference > 0);
unchangedCases = sum(caseDifference == 0);

%% 3. Wilcoxon paired test
[pValue,hValue,statistics] = signrank( ...
    timeCaseMAE, ...
    ridgeCaseMAE, ...
    "method","exact");

fprintf("========== Paired case-level test ==========\n");
fprintf("Improved cases: %d\n",improvedCases);
fprintf("Worsened cases: %d\n",worsenedCases);
fprintf("Unchanged cases: %d\n",unchangedCases);
fprintf("Wilcoxon p-value: %.6f\n",pValue);
fprintf("Reject null hypothesis at 0.05: %d\n",hValue);

if isfield(statistics,"signedrank")
    fprintf("Signed-rank statistic: %.4f\n", ...
        statistics.signedrank);
end

%% 4. Case-clustered bootstrap
numberOfBootstrapSamples = 100000;

rng(20260716,"twister");

% Each column represents one bootstrap resampling
bootstrapCaseIndex = randi( ...
    numberOfCases, ...
    numberOfCases, ...
    numberOfBootstrapSamples);

bootstrapSampleCount = ...
    sum(sampleCount(bootstrapCaseIndex),1);

bootstrapRidgeMAE = ...
    sum(ridgeErrorSum(bootstrapCaseIndex),1) ./ ...
    bootstrapSampleCount;

bootstrapTimeMAE = ...
    sum(timeErrorSum(bootstrapCaseIndex),1) ./ ...
    bootstrapSampleCount;

bootstrapDifference = ...
    bootstrapTimeMAE-bootstrapRidgeMAE;

ridgeConfidenceInterval = ...
    prctile(bootstrapRidgeMAE,[2.5 97.5]);

timeConfidenceInterval = ...
    prctile(bootstrapTimeMAE,[2.5 97.5]);

differenceConfidenceInterval = ...
    prctile(bootstrapDifference,[2.5 97.5]);

improvementProbability = ...
    mean(bootstrapDifference < 0);

%% 5. Overall improvement
ridgeOverallMAE = mean(abs( ...
    predRidgeGated-actualVB));

timeOverallMAE = mean(abs( ...
    predTimeGated-actualVB));

maeDifference = ...
    timeOverallMAE-ridgeOverallMAE;

improvementPercent = ...
    100*(ridgeOverallMAE-timeOverallMAE) / ...
    ridgeOverallMAE;

fprintf("\n========== Clustered bootstrap ==========\n");

fprintf("RidgeGated MAE: %.6f\n", ...
    ridgeOverallMAE);

fprintf("RidgeGated 95%% CI: [%.6f, %.6f]\n", ...
    ridgeConfidenceInterval(1), ...
    ridgeConfidenceInterval(2));

fprintf("TimeGated MAE: %.6f\n", ...
    timeOverallMAE);

fprintf("TimeGated 95%% CI: [%.6f, %.6f]\n", ...
    timeConfidenceInterval(1), ...
    timeConfidenceInterval(2));

fprintf("MAE difference (Time - Ridge): %.6f\n", ...
    maeDifference);

fprintf("Difference 95%% CI: [%.6f, %.6f]\n", ...
    differenceConfidenceInterval(1), ...
    differenceConfidenceInterval(2));

fprintf("MAE improvement: %.2f%%\n", ...
    improvementPercent);

fprintf("Bootstrap probability of improvement: %.4f\n", ...
    improvementProbability);

%% 6. Save tables
caseStatisticalTable = table( ...
    caseList,sampleCount, ...
    ridgeCaseMAE,timeCaseMAE, ...
    caseDifference, ...
    'VariableNames', ...
    {'CaseID','SampleCount', ...
     'RidgeGatedMAE','TimeGatedMAE', ...
     'TimeMinusRidge'});

overallStatisticalTable = table( ...
    ridgeOverallMAE, ...
    timeOverallMAE, ...
    maeDifference, ...
    improvementPercent, ...
    pValue, ...
    improvementProbability, ...
    ridgeConfidenceInterval(1), ...
    ridgeConfidenceInterval(2), ...
    timeConfidenceInterval(1), ...
    timeConfidenceInterval(2), ...
    differenceConfidenceInterval(1), ...
    differenceConfidenceInterval(2), ...
    improvedCases,worsenedCases, ...
    'VariableNames', ...
    {'RidgeMAE','TimeMAE','MAEDifference', ...
     'ImprovementPercent','WilcoxonP', ...
     'BootstrapImprovementProbability', ...
     'RidgeCILower','RidgeCIUpper', ...
     'TimeCILower','TimeCIUpper', ...
     'DifferenceCILower','DifferenceCIUpper', ...
     'ImprovedCases','WorsenedCases'});

writetable( ...
    caseStatisticalTable, ...
    fullfile(resultFolder, ...
    "statistical_case_results.csv"));

writetable( ...
    overallStatisticalTable, ...
    fullfile(resultFolder, ...
    "statistical_overall_results.csv"));

%% 7. Plot
fig = figure( ...
    "Color","w", ...
    "Position",[100 100 1300 520]);

tiledlayout(1,2, ...
    "TileSpacing","compact", ...
    "Padding","compact");

nexttile;
hold on;

for caseIndex = 1:numberOfCases
    plot([1 2], ...
        [ridgeCaseMAE(caseIndex), ...
         timeCaseMAE(caseIndex)], ...
        "-o", ...
        "LineWidth",1);
end

hold off;
grid on;

xlim([0.8 2.2]);
xticks([1 2]);
xticklabels(["RidgeGated","TimeGated"]);
ylabel("Case-level MAE");
title("Paired Case-Level Comparison");

nexttile;

histogram( ...
    bootstrapDifference, ...
    60, ...
    "Normalization","probability");

hold on;
xline(0,"r--","LineWidth",1.5);
xline(mean(bootstrapDifference), ...
    "k-","LineWidth",1.5);
hold off;

grid on;
xlabel("MAE difference: TimeGated - RidgeGated");
ylabel("Probability");
title("Case-Clustered Bootstrap");

exportgraphics( ...
    fig, ...
    fullfile(resultFolder, ...
    "statistical_validation.png"), ...
    "Resolution",300);