clear; clc; close all;

paperRoot=fileparts(mfilename('fullpath'));
resultDir=fullfile(paperRoot,'additional_validation_results','reviewer_improvements');

early=readtable(fullfile(resultDir,'early_window_overall.csv'), ...
    'VariableNamingRule','preserve','TextType','string');
earlyStats=readtable(fullfile(resultDir,'early_window_statistics.csv'), ...
    'VariableNamingRule','preserve','TextType','string');
randomFault=readtable(fullfile(resultDir,'random_fault_statistics.csv'), ...
    'VariableNamingRule','preserve','TextType','string');
repeatVariability=readtable(fullfile(resultDir,'random_fault_repeat_variability.csv'), ...
    'VariableNamingRule','preserve','TextType','string');
detection=readtable(fullfile(resultDir,'random_fault_detection_summary.csv'), ...
    'VariableNamingRule','preserve','TextType','string');
phmAudit=readtable(fullfile(resultDir,'phm_segmentation_cutter_audit.csv'), ...
    'VariableNamingRule','preserve','TextType','string');
phmConclusion=readtable(fullfile(resultDir,'phm_segmentation_conclusion.csv'), ...
    'VariableNamingRule','preserve','TextType','string');
phmSensitivity=readtable(fullfile(resultDir,'phm_segmentation_sensitivity.csv'), ...
    'VariableNamingRule','preserve','TextType','string');

%% Headline machine-readable evidence
EvidenceArea=strings(0,1); Endpoint=strings(0,1); Value=zeros(0,1);
Unit=strings(0,1); IndependentUnit=strings(0,1); Interpretation=strings(0,1);
append=@(area,endpoint,value,unit,n,note) struct( ...
    'area',area,'endpoint',endpoint,'value',value,'unit',unit,'n',n,'note',note);
rows=repmat(append("","",0,"","",""),0,1);

fullWindow=early(early.StableWindowFraction==1,:);
halfWindow=early(early.StableWindowFraction==0.5,:);
quarterWindow=early(early.StableWindowFraction==0.25,:);
quarterStat=earlyStats(earlyStats.ComparatorFraction==0.25,:);
halfStat=earlyStats(earlyStats.ComparatorFraction==0.5,:);
combinedFault=randomFault(randomFault.Dataset=="Combined",:);
nuaaFault=randomFault(randomFault.Dataset=="NUAA",:);
phmFault=randomFault(randomFault.Dataset=="PHM2010",:);

rows(end+1)=append("Early prediction","Full stable-window MAE",fullWindow.MAE,"VB", ...
    "146 records nested in 16 cases","Locked reference model");
rows(end+1)=append("Early prediction","50% stable-window MAE",halfWindow.MAE,"VB", ...
    "146 records nested in 16 cases","Prediction available at mean 18 s");
rows(end+1)=append("Early prediction","25% stable-window MAE",quarterWindow.MAE,"VB", ...
    "146 records nested in 16 cases","Prediction available at mean 13.5 s");
rows(end+1)=append("Early prediction","25% vs full Holm p",quarterStat.HolmAdjustedP, ...
    "p-value","16 paired cases","No conclusive loss of case-level accuracy");
rows(end+1)=append("Early prediction","50% vs full Holm p",halfStat.HolmAdjustedP, ...
    "p-value","16 paired cases","No conclusive difference");
rows(end+1)=append("Computational profile","25% feature extraction time", ...
    quarterWindow.FeatureExtractionMillisecondsPerRecord,"ms per record", ...
    "146 records; median of 3 timed passes","MATLAB desktop measurement");
rows(end+1)=append("Computational profile","Full-window feature extraction time", ...
    fullWindow.FeatureExtractionMillisecondsPerRecord,"ms per record", ...
    "146 records; median of 3 timed passes","MATLAB desktop measurement");

rows(end+1)=append("Randomized multi-fault","Combined relative MAE improvement", ...
    combinedFault.RelativeImprovementPercent,"percent", ...
    "12 independent experiments/cutters; 30 technical repeats averaged", ...
    "Random location, duration, direction, and severity");
rows(end+1)=append("Randomized multi-fault","Combined Holm-adjusted p", ...
    combinedFault.HolmAdjustedP,"p-value","12 paired independent units", ...
    "Multiplicity controlled across NUAA, PHM2010, and combined analyses");
rows(end+1)=append("Randomized multi-fault","Combined bootstrap CI lower", ...
    combinedFault.BootstrapCILower,"relative MAE","12 experiment clusters", ...
    "Automatic gate minus full sensors");
rows(end+1)=append("Randomized multi-fault","Combined bootstrap CI upper", ...
    combinedFault.BootstrapCIUpper,"relative MAE","12 experiment clusters", ...
    "Automatic gate minus full sensors");
rows(end+1)=append("Randomized multi-fault","NUAA relative MAE improvement", ...
    nuaaFault.RelativeImprovementPercent,"percent","9 independent experiments", ...
    "8/9 units improved");
rows(end+1)=append("Randomized multi-fault","PHM2010 relative MAE improvement", ...
    phmFault.RelativeImprovementPercent,"percent","3 independent cutters", ...
    "2/3 units improved; small-n result not significant");

rows(end+1)=append("PHM segmentation","Cuts detected per cutter", ...
    min(phmAudit.TimestampRunCount),"cuts per cutter","3 cutters", ...
    "Matches the 315-cut protocol for c1, c4, and c6");
rows(end+1)=append("PHM segmentation","Cadence separation ratio", ...
    phmConclusion.MinimumCadenceSeparationRatio,"fold","3 cutters", ...
    "Minimum within-cut gap divided by maximum boundary gap");
rows(end+1)=append("PHM segmentation","Stable threshold minimum", ...
    phmConclusion.StableMultiplierMinimum,"cadence multiplier","3 cutters", ...
    "Identical grouping through the stable interval");
rows(end+1)=append("PHM segmentation","Stable threshold maximum", ...
    phmConclusion.StableMultiplierMaximum,"cadence multiplier","3 cutters", ...
    "Identical grouping through the stable interval");
rows(end+1)=append("PHM segmentation","Timestamp boundaries with repeated wear", ...
    phmConclusion.RepeatedWearTimestampBoundaryN,"boundaries","3 cutters", ...
    "Evidence that label-change grouping would merge distinct cuts");

for rowIndex=1:numel(rows)
    EvidenceArea(rowIndex,1)=rows(rowIndex).area;
    Endpoint(rowIndex,1)=rows(rowIndex).endpoint;
    Value(rowIndex,1)=rows(rowIndex).value;
    Unit(rowIndex,1)=rows(rowIndex).unit;
    IndependentUnit(rowIndex,1)=rows(rowIndex).n;
    Interpretation(rowIndex,1)=rows(rowIndex).note;
end
master=table(EvidenceArea,Endpoint,Value,Unit,IndependentUnit,Interpretation);
writetable(master,fullfile(resultDir,'reviewer_improvement_master_summary.csv'));

%% Updated reviewer-risk matrix
ReviewerRisk=[ ...
    "Only end-of-cut performance; online value unclear"; ...
    "Artificial faults use fixed locations and severities"; ...
    "PHM run segmentation may use wear labels"; ...
    "PHM segmentation threshold may be arbitrary"; ...
    "Technical repeats may be treated as independent n"; ...
    "Gate may fail for realistic vibration bias/noise"; ...
    "Repeated model development reused the 16 NASA cases"; ...
    "No real annotated sensor-fault dataset or machine deployment"; ...
    "External validation is not direct cross-domain transfer"];
ActionImplemented=[ ...
    "Strict LOCO at 25/50/75/100% of the predefined stable region plus measured MATLAB latency"; ...
    "Thirty reruns with randomized start, contiguous duration, bias direction, and severity"; ...
    "Timestamp-only grouping; wear labels accessed only after segmentation for audit"; ...
    "Ten threshold multipliers spanning failure and stable regimes"; ...
    "Average 30 simulations inside each experiment/cutter before Wilcoxon and bootstrap"; ...
    "Per-sensor/per-fault detection and performance table reports negative scenarios"; ...
    "Final protocol frozen after this audit; limitation retained explicitly"; ...
    "Not removable with current public data; bounded claim retained"; ...
    "Terminology changed to multi-dataset replication and robustness validation"];
Evidence=[ ...
    "50% window MAE 0.10849 at mean 18 s; 25% MAE 0.11135 at mean 13.5 s"; ...
    "Combined improvement 22.24%; Holm p=0.01465; cluster CI [-0.5314,-0.1187]"; ...
    "315 cuts for each cutter; 140 timestamp boundaries have repeated wear labels"; ...
    "Grouping identical for cadence multipliers 0.001-0.7; cadence regimes separated 2000-fold"; ...
    "n=9 NUAA experiments, n=3 PHM cutters, n=12 combined"; ...
    "Low detection and small negative gains remain for selected vibration bias/noise scenarios"; ...
    "Transparency action only; cannot recreate a prospectively untouched NASA test set"; ...
    "Artificial-fault evidence supports robustness under simulated faults only"; ...
    "Each dataset is trained and validated separately"];
Status=["Addressed";"Addressed";"Addressed";"Addressed";"Addressed"; ...
    "Quantified limitation";"Residual limitation";"Residual limitation";"Terminology corrected"];
ManuscriptClaim=[ ...
    "Early prediction within the stable cutting segment, not demonstrated machine-controller deployment"; ...
    "Robust to a randomized family of simulated sensor faults"; ...
    "PHM cuts reconstructed without target labels"; ...
    "Segmentation is insensitive throughout a broad physically separated threshold interval"; ...
    "Simulation reruns are technical repeats and are not counted as independent experiments"; ...
    "Average robustness improves, but detection is fault- and sensor-dependent"; ...
    "Results require future prospective replication"; ...
    "Do not claim validation on real hardware faults"; ...
    "Do not call the current experiment cross-domain transfer"];
riskMatrix=table(ReviewerRisk,ActionImplemented,Evidence,Status,ManuscriptClaim);
writetable(riskMatrix,fullfile(resultDir,'reviewer_risk_matrix_updated.csv'));

%% Consolidated figure
figure('Color','w','Position',[60 60 1500 980]);
tiledlayout(2,2,'Padding','compact','TileSpacing','compact');
nexttile;
plot(100*early.StableWindowFraction,early.MAE,'-o','LineWidth',2, ...
    'MarkerFaceColor',[0.25 0.55 0.78]); hold on;
plot(100*early.StableWindowFraction,early.RMSE,'-s','LineWidth',2, ...
    'MarkerFaceColor',[0.90 0.30 0.08]);
xlabel('Available stable-region fraction (%)'); ylabel('Error (VB)');
legend({'MAE','RMSE'},'Location','best'); grid on;
title('(a) Early-window prediction');

nexttile;
yyaxis left;
bar(100*early.StableWindowFraction,early.MeanObservationEndpointSeconds, ...
    'FaceColor',[0.25 0.55 0.78]); ylabel('Observation endpoint (s)');
yyaxis right;
plot(100*early.StableWindowFraction, ...
    early.TotalOnlineComputeMillisecondsPerRecord,'-o','LineWidth',2, ...
    'Color',[0.90 0.30 0.08]); ylabel('Compute time (ms/record)');
xlabel('Available stable-region fraction (%)'); grid on;
title('(b) Observation and computation latency');

nexttile;
histogram(repeatVariability.RelativeImprovementPercent,10, ...
    'FaceColor',[0.25 0.55 0.78]); hold on;
xline(mean(repeatVariability.RelativeImprovementPercent),'--','Mean', ...
    'LineWidth',2,'Color',[0.90 0.30 0.08]);
xlabel('Relative MAE improvement (%)'); ylabel('Randomization repeats'); grid on;
title('(c) Thirty randomized fault realizations');

nexttile;
for cutterIndex=1:numel(unique(phmSensitivity.Cutter,'stable'))
    current=unique(phmSensitivity.Cutter,'stable');
    mask=phmSensitivity.Cutter==current(cutterIndex);
    semilogx(phmSensitivity.ThresholdMultiplier(mask), ...
        phmSensitivity.DetectedRunCount(mask),'-o','LineWidth',2); hold on;
end
yline(315,'--','Expected 315','LineWidth',1.5);
set(gca,'YScale','log'); ylim([1 1e5]);
xlabel('Threshold / typical timestamp cadence'); ylabel('Detected cuts'); grid on;
legend(unique(phmSensitivity.Cutter,'stable'),'Location','northwest');
title('(d) Label-free PHM segmentation sensitivity');

sgtitle('Reviewer-Directed Validation of Early Prediction and Robustness', ...
    'FontWeight','bold');
set(gcf,'ToolBar','none'); axesHandles=findall(gcf,'Type','axes');
for axisIndex=1:numel(axesHandles)
    if isprop(axesHandles(axisIndex),'Toolbar') && ~isempty(axesHandles(axisIndex).Toolbar)
        axesHandles(axisIndex).Toolbar.Visible='off';
    end
end
drawnow;
exportgraphics(gcf,fullfile(resultDir,'reviewer_improvement_overview.png'),'Resolution',300);
exportgraphics(gcf,fullfile(resultDir,'reviewer_improvement_overview.pdf'),'ContentType','vector');

save(fullfile(resultDir,'reviewer_improvement_compiled.mat'), ...
    'master','riskMatrix','early','earlyStats','randomFault', ...
    'repeatVariability','detection','phmAudit','phmConclusion','phmSensitivity');

%% Output manifest
listing=dir(fullfile(resultDir,'*')); listing=listing(~[listing.isdir]);
File=string({listing.name})'; Bytes=[listing.bytes]'; LastModified=string({listing.date})';
manifest=table(File,Bytes,LastModified);
writetable(manifest,fullfile(resultDir,'reviewer_improvement_manifest.csv'));

fprintf('\n========== Reviewer-directed improvement summary ==========\n'); disp(master);
fprintf('\nSaved to:\n%s\n',resultDir);
