paperRoot = fileparts(mfilename('fullpath'));
clear;
clc;
close all;

%% 1. 路径
filePath = ...
    fullfile(paperRoot, 'mill', 'mill.mat');

resultFolder = ...
    fullfile(paperRoot, 'mill', 'results');

%% 2. 读取数据
raw = load(filePath);
mill = raw.mill;

featureData = load( ...
    fullfile(resultFolder, ...
    "run_level_features.mat"));

featureTable = featureData.featureTable;

nSamples = height(featureTable);

%% 3. 计算smcDC饱和比例
smcDCSaturationRatio = nan(nSamples,1);
smcDCSaturationFlag1 = false(nSamples,1);
smcDCSaturationFlag50 = false(nSamples,1);

% 发布数据中经验观察到的smcDC最高离散码值与码间隔。
% 随附文档未给出采集板量程，因此不将其表述为硬件规格。
empiricalTopCode = 9.9951171875;
empiricalCodeStep = 0.0048828125;
saturationThreshold = empiricalTopCode-empiricalCodeStep;

for row = 1:nSamples

    sourceIndex = ...
        featureTable.OriginalIndex(row);

    x = double( ...
        mill(sourceIndex).smcDC(:));

    n = numel(x);

    startIndex = floor(0.25*n)+1;
    endIndex = floor(0.75*n);

    xCentral = x(startIndex:endIndex);

    currentRatio = mean( ...
        xCentral >= saturationThreshold);

    smcDCSaturationRatio(row) = ...
        currentRatio;

    smcDCSaturationFlag1(row) = ...
        currentRatio >= 0.01;

    smcDCSaturationFlag50(row) = ...
        currentRatio >= 0.50;
end

%% 4. 添加质量变量
qualityAwareTable = featureTable;

qualityAwareTable.smcDC_SaturationRatio = ...
    smcDCSaturationRatio;

qualityAwareTable.smcDC_SaturationFlag1 = ...
    double(smcDCSaturationFlag1);

qualityAwareTable.smcDC_SaturationFlag50 = ...
    double(smcDCSaturationFlag50);

%% 5. 总体统计
fprintf("========== smcDC固定阈值饱和统计 ==========\n");
fprintf("有效样本数：%d\n",nSamples);
fprintf("饱和比例 >= 1%%：%d\n", ...
    sum(smcDCSaturationFlag1));
fprintf("饱和比例 >= 50%%：%d\n", ...
    sum(smcDCSaturationFlag50));
fprintf("饱和比例 = 100%%：%d\n", ...
    sum(smcDCSaturationRatio >= 0.9999));

%% 6. 按案例统计
caseList = unique(qualityAwareTable.CaseID);
nCases = numel(caseList);

SampleCount = nan(nCases,1);
SaturatedAbove1 = nan(nCases,1);
SaturatedAbove50 = nan(nCases,1);
FullySaturated = nan(nCases,1);
MeanSaturationRatio = nan(nCases,1);
MaximumSaturationRatio = nan(nCases,1);

for k = 1:nCases

    mask = ...
        qualityAwareTable.CaseID == ...
        caseList(k);

    SampleCount(k) = sum(mask);

    SaturatedAbove1(k) = sum( ...
        smcDCSaturationRatio(mask) >= 0.01);

    SaturatedAbove50(k) = sum( ...
        smcDCSaturationRatio(mask) >= 0.50);

    FullySaturated(k) = sum( ...
        smcDCSaturationRatio(mask) >= 0.9999);

    MeanSaturationRatio(k) = mean( ...
        smcDCSaturationRatio(mask));

    MaximumSaturationRatio(k) = max( ...
        smcDCSaturationRatio(mask));
end

caseSaturationSummary = table( ...
    caseList, ...
    SampleCount, ...
    SaturatedAbove1, ...
    SaturatedAbove50, ...
    FullySaturated, ...
    MeanSaturationRatio, ...
    MaximumSaturationRatio, ...
    'VariableNames', ...
    {'CaseID','SampleCount', ...
     'SaturatedAbove1Percent', ...
     'SaturatedAbove50Percent', ...
     'FullySaturated', ...
     'MeanSaturationRatio', ...
     'MaximumSaturationRatio'});

fprintf("\n========== 各案例smcDC饱和统计 ==========\n");
disp(caseSaturationSummary);

%% 7. 显示饱和最严重的记录
displayTable = qualityAwareTable(:,{ ...
    'OriginalIndex', ...
    'CaseID', ...
    'RunID', ...
    'VB', ...
    'DOC', ...
    'Feed', ...
    'Material', ...
    'smcDC_SaturationRatio'});

displayTable = sortrows( ...
    displayTable, ...
    "smcDC_SaturationRatio", ...
    "descend");

fprintf("\n========== 饱和最严重的20条记录 ==========\n");
disp(displayTable(1:20,:));

%% 8. 绘制饱和比例与VB关系
figure( ...
    "Color","w", ...
    "Position",[100 100 1100 700]);

scatter( ...
    qualityAwareTable.VB, ...
    smcDCSaturationRatio, ...
    45, ...
    qualityAwareTable.CaseID, ...
    "filled");

grid on;
xlabel("Flank wear VB");
ylabel("smcDC saturation ratio");
title("smcDC Saturation Ratio versus Tool Wear");
colorbar;

%% 9. 保存
save( ...
    fullfile(resultFolder, ...
    "quality_aware_features.mat"), ...
    "qualityAwareTable", ...
    "caseSaturationSummary", ...
    "saturationThreshold");

writetable( ...
    qualityAwareTable, ...
    fullfile(resultFolder, ...
    "quality_aware_features.csv"));

writetable( ...
    caseSaturationSummary, ...
    fullfile(resultFolder, ...
    "case_saturation_summary.csv"));

exportgraphics( ...
    gcf, ...
    fullfile(resultFolder, ...
    "smcDC_saturation_vs_VB.png"), ...
    "Resolution",300);
