paperRoot = fileparts(mfilename('fullpath'));
clear;
clc;
close all;

%% 1. Paths and helper functions
scriptFolder = fileparts(mfilename("fullpath"));
addpath(scriptFolder);

assert(exist("groupedRidgePrediction","file") == 2, ...
    "groupedRidgePrediction.m was not found.");

assert(exist("groupedGatedRidgePrediction","file") == 2, ...
    "groupedGatedRidgePrediction.m was not found.");

resultFolder = ...
    fullfile(paperRoot, 'mill', 'results');

%% 2. Load data
timeData = load(fullfile( ...
    resultFolder, ...
    "quality_aware_with_time.mat"));

modelData = load(fullfile( ...
    resultFolder, ...
    "time_model_results.mat"));

T = timeData.timeAwareTable;
baselineTable = modelData.predictionTable;

assert(isequal( ...
    T.OriginalIndex, ...
    baselineTable.OriginalIndex), ...
    "The data orders are inconsistent.");

%% 3. Basic variables
y = T.VB;
caseID = T.CaseID;
caseList = unique(caseID);

numberOfSamples = height(T);
numberOfCases = numel(caseList);

elapsedTime = T.ElapsedTime;
elapsedTimeSquared = elapsedTime.^2;

saturationRatio = ...
    T.smcDC_SaturationRatio;

XProcess = T{:,{'DOC','Feed','Material'}};

allVariableNames = ...
    string(T.Properties.VariableNames);

sensorVariableNames = ...
    allVariableNames(8:85);

smcDCMask = startsWith( ...
    sensorVariableNames,"smcDC_");

otherSensorNames = ...
    sensorVariableNames(~smcDCMask);

%% 4. Sensor groups
sensorGroups = [ ...
    "smcAC", ...
    "smcDC", ...
    "vib_table", ...
    "vib_spindle", ...
    "AE_table", ...
    "AE_spindle"];

numberOfSensors = numel(sensorGroups);

modelNames = [ ...
    "Baseline_TimeGated"; ...
    "Remove_" + sensorGroups'];

numberOfModels = numel(modelNames);

predictionMatrix = ...
    nan(numberOfSamples,numberOfModels);

% Existing baseline prediction
predictionMatrix(:,1) = ...
    baselineTable.PredTimeGated;

lambdaGrid = logspace(-4,4,17);
gateThresholdGrid = [0.01 0.10 0.50];

bestLambdaAll = ...
    nan(numberOfCases,numberOfSensors);

bestLambdaQuality = ...
    nan(numberOfCases,numberOfSensors);

bestGateThreshold = ...
    nan(numberOfCases,numberOfSensors);

%% 5. Leave-one-sensor-out models
for sensorIndex = 1:numberOfSensors

    currentSensor = sensorGroups(sensorIndex);

    fprintf( ...
        "\n========== Removing %s ==========\n", ...
        currentSensor);

    if currentSensor == "smcDC"

        % Completely remove smcDC:
        % no conventional smcDC features,
        % no saturation ratio and no gate.
        XRemoved = [ ...
            XProcess, ...
            T{:,cellstr(otherSensorNames)}, ...
            elapsedTime, ...
            elapsedTimeSquared];

        currentPrediction = ...
            nan(numberOfSamples,1);

        fprintf("Input dimension: %d\n", ...
            size(XRemoved,2));

        for caseIndex = 1:numberOfCases

            testCase = caseList(caseIndex);

            testMask = caseID == testCase;
            trainMask = ~testMask;

            fprintf("  Testing Case %d\n",testCase);

            [testPrediction,bestLambda] = ...
                groupedRidgePrediction( ...
                XRemoved,y,caseID, ...
                trainMask,testMask, ...
                lambdaGrid);

            currentPrediction(testMask) = ...
                testPrediction;

            bestLambdaAll( ...
                caseIndex,sensorIndex) = ...
                bestLambda;
        end

        predictionMatrix(:,sensorIndex+1) = ...
            currentPrediction;

    else

        % Remove this sensor from both branches
        currentPrefix = currentSensor + "_";

        allKeepMask = ~startsWith( ...
            sensorVariableNames,currentPrefix);

        qualityKeepMask = ~startsWith( ...
            otherSensorNames,currentPrefix);

        allKeptNames = ...
            sensorVariableNames(allKeepMask);

        qualityKeptNames = ...
            otherSensorNames(qualityKeepMask);

        XAllRemoved = [ ...
            XProcess, ...
            T{:,cellstr(allKeptNames)}, ...
            elapsedTime, ...
            elapsedTimeSquared];

        XQualityRemoved = [ ...
            XProcess, ...
            T{:,cellstr(qualityKeptNames)}, ...
            elapsedTime, ...
            elapsedTimeSquared];

        fprintf( ...
            "All branch dimension: %d\n", ...
            size(XAllRemoved,2));

        fprintf( ...
            "Quality branch dimension: %d\n", ...
            size(XQualityRemoved,2));

        predictionAll = ...
            nan(numberOfSamples,1);

        predictionQuality = ...
            nan(numberOfSamples,1);

        gatedPrediction = ...
            nan(numberOfSamples,1);

        for caseIndex = 1:numberOfCases

            testCase = caseList(caseIndex);

            testMask = caseID == testCase;
            trainMask = ~testMask;

            fprintf("  Testing Case %d\n",testCase);

            [testPredictionAll,testPredictionQuality, ...
                testPredictionGated,lambdaAll,lambdaQuality, ...
                selectedThreshold] = ...
                groupedGatedRidgePrediction( ...
                XAllRemoved,XQualityRemoved,saturationRatio, ...
                y,caseID,trainMask,testMask,lambdaGrid, ...
                gateThresholdGrid);

            predictionAll(testMask) = ...
                testPredictionAll;

            predictionQuality(testMask) = ...
                testPredictionQuality;

            gatedPrediction(testMask) = ...
                testPredictionGated;

            bestLambdaAll( ...
                caseIndex,sensorIndex) = ...
                lambdaAll;

            bestLambdaQuality( ...
                caseIndex,sensorIndex) = ...
                lambdaQuality;

            bestGateThreshold( ...
                caseIndex,sensorIndex) = ...
                selectedThreshold;
        end

        predictionMatrix(:,sensorIndex+1) = ...
            gatedPrediction;
    end
end

%% 6. Overall metrics
MAE = nan(numberOfModels,1);
RMSE = nan(numberOfModels,1);
R2 = nan(numberOfModels,1);
P95AbsoluteError = nan(numberOfModels,1);
MaximumAbsoluteError = nan(numberOfModels,1);

for modelIndex = 1:numberOfModels

    residual = ...
        predictionMatrix(:,modelIndex)-y;

    absoluteError = abs(residual);

    MAE(modelIndex) = mean(absoluteError);
    RMSE(modelIndex) = sqrt(mean(residual.^2));

    R2(modelIndex) = 1- ...
        sum(residual.^2)/ ...
        sum((y-mean(y)).^2);

    P95AbsoluteError(modelIndex) = ...
        prctile(absoluteError,95);

    MaximumAbsoluteError(modelIndex) = ...
        max(absoluteError);
end

MAEChange = MAE-MAE(1);

MAEChangePercent = ...
    100*MAEChange/MAE(1);

overallResults = table( ...
    modelNames,MAE,RMSE,R2, ...
    P95AbsoluteError, ...
    MaximumAbsoluteError, ...
    MAEChange,MAEChangePercent);

fprintf("\n========== Sensor ablation results ==========\n");
disp(overallResults);

fprintf( ...
    "Positive MAEChange means performance worsened after removal.\n");

%% 7. Case-level results
caseMAE = nan(numberOfCases,numberOfModels);
caseSampleCount = nan(numberOfCases,1);

for caseIndex = 1:numberOfCases

    mask = caseID == caseList(caseIndex);
    caseSampleCount(caseIndex) = sum(mask);

    for modelIndex = 1:numberOfModels

        caseMAE(caseIndex,modelIndex) = ...
            mean(abs( ...
            predictionMatrix(mask,modelIndex)- ...
            y(mask)));
    end
end

longCaseID = repmat( ...
    caseList,numberOfModels,1);

longSampleCount = repmat( ...
    caseSampleCount,numberOfModels,1);

longModelName = repelem( ...
    modelNames,numberOfCases,1);

longCaseMAE = caseMAE(:);

caseResults = table( ...
    longCaseID,longSampleCount, ...
    longModelName,longCaseMAE, ...
    'VariableNames', ...
    {'CaseID','SampleCount','Model','MAE'});

%% 8. Plot
fig = figure( ...
    "Color","w", ...
    "Position",[100 100 1200 560]);

xLabels = categorical(sensorGroups);
xLabels = reordercats( ...
    xLabels,cellstr(sensorGroups));

bar(xLabels,MAEChange(2:end));

hold on;
yline(0,"k--","LineWidth",1.2);
hold off;

grid on;
ylabel("MAE change after sensor removal");
xlabel("Removed sensor");
title("Leave-One-Sensor-Out Ablation");

subtitle( ...
    "Positive values indicate that the removed sensor was useful");

currentAxis = gca;
if ~isempty(currentAxis.Toolbar)
    currentAxis.Toolbar.Visible = "off";
end
disableDefaultInteractivity(currentAxis);
drawnow;

%% 9. Save
predictionTable = table( ...
    T.OriginalIndex,caseID,T.RunID,y, ...
    'VariableNames', ...
    {'OriginalIndex','CaseID','RunID','ActualVB'});

for modelIndex = 1:numberOfModels

    validName = matlab.lang.makeValidName( ...
        modelNames(modelIndex));

    predictionTable.(validName) = ...
        predictionMatrix(:,modelIndex);
end

writetable( ...
    overallResults, ...
    fullfile(resultFolder, ...
    "sensor_ablation_overall.csv"));

writetable( ...
    caseResults, ...
    fullfile(resultFolder, ...
    "sensor_ablation_cases.csv"));

writetable( ...
    predictionTable, ...
    fullfile(resultFolder, ...
    "sensor_ablation_predictions.csv"));

save( ...
    fullfile(resultFolder, ...
    "sensor_ablation_results.mat"), ...
    "overallResults","caseResults", ...
    "predictionTable","predictionMatrix", ...
    "bestLambdaAll","bestLambdaQuality", ...
    "bestGateThreshold","gateThresholdGrid");

exportgraphics( ...
    fig, ...
    fullfile(resultFolder, ...
    "sensor_ablation.png"), ...
    "Resolution",300);
