paperRoot = fileparts(mfilename('fullpath'));
clear;
clc;
close all;

%% 1. Paths and required helper functions
scriptFolder = fileparts(mfilename("fullpath"));
addpath(scriptFolder);

assert(exist("groupedRidgePrediction","file") == 2, ...
    "groupedRidgePrediction.m was not found.");

assert(exist("fitRidgeAndPredict","file") == 2, ...
    "fitRidgeAndPredict.m was not found.");

assert(exist("groupedGatedRidgePrediction","file") == 2, ...
    "groupedGatedRidgePrediction.m was not found.");

dataFile = ...
    fullfile(paperRoot, 'mill', 'mill.mat');

resultFolder = ...
    fullfile(paperRoot, 'mill', 'results');

%% 2. Load raw signals and existing clean feature table
rawData = load(dataFile);
mill = rawData.mill;

timeData = load(fullfile( ...
    resultFolder, ...
    "quality_aware_with_time.mat"));

T = timeData.timeAwareTable;

y = T.VB;
caseID = T.CaseID;
originalIndex = T.OriginalIndex;

caseList = unique(caseID);
numberOfCases = numel(caseList);
numberOfSamples = height(T);

%% 3. Reconstruct the two clean model branches
allVariableNames = ...
    string(T.Properties.VariableNames);

sensorVariableNames = ...
    allVariableNames(8:85);

smcDCFeatureMask = startsWith( ...
    sensorVariableNames,"smcDC_");

otherSensorNames = ...
    sensorVariableNames(~smcDCFeatureMask);

XProcess = T{:,{'DOC','Feed','Material'}};

XAllSensors = ...
    T{:,cellstr(sensorVariableNames)};

XOtherSensors = ...
    T{:,cellstr(otherSensorNames)};

elapsedTime = T.ElapsedTime;
elapsedTimeSquared = elapsedTime.^2;

originalSaturationRatio = ...
    T.smcDC_SaturationRatio;

XAllSensorsTime = [ ...
    XProcess, ...
    XAllSensors, ...
    elapsedTime, ...
    elapsedTimeSquared];

XQualityAwareTime = [ ...
    XProcess, ...
    XOtherSensors, ...
    elapsedTime, ...
    elapsedTimeSquared];

% Column positions in the two input matrices
smcDCInputColumns = ...
    3 + find(smcDCFeatureMask);

fprintf("AllSensorsTime dimension: %d\n", ...
    size(XAllSensorsTime,2));

fprintf("QualityAwareTime dimension: %d\n", ...
    size(XQualityAwareTime,2));

%% 4. Artificial saturation settings
Fs = 250;

% Empirical top code and one-code margin observed in the released smcDC
% signal grid. These values are not claimed as a documented hardware range.
saturationRail = 9.9951171875;
quantizationStep = 0.0048828125;
saturationThreshold = saturationRail-quantizationStep;
cleanEligibilityThreshold = 0.01;
gateThresholdGrid = [0.01 0.10 0.50];

injectionLevels = [ ...
    0,0.10,0.30,0.50,0.70,1.00];

numberOfLevels = numel(injectionLevels);
numberOfInjectionRepeats = 10;

% Only originally clean records are evaluated.
% Natural saturated records are not mixed into this experiment.
eligibleMask = ...
    originalSaturationRatio < cleanEligibilityThreshold;

numberOfEligibleSamples = sum(eligibleMask);

fprintf("\n========== Injection experiment setup ==========\n");
fprintf("All valid records: %d\n",numberOfSamples);
fprintf("Originally clean records used for injection: %d\n", ...
    numberOfEligibleSamples);
fprintf("Injection repetitions per level: %d\n", ...
    numberOfInjectionRepeats);

%% 5. Allocate predictions
predAllSensors = nan( ...
    numberOfSamples,numberOfLevels, ...
    numberOfInjectionRepeats);

predQualityAware = nan( ...
    numberOfSamples,numberOfLevels, ...
    numberOfInjectionRepeats);

predQualityGated = nan( ...
    numberOfSamples,numberOfLevels, ...
    numberOfInjectionRepeats);

actualInjectedRatio = nan( ...
    numberOfSamples,numberOfLevels, ...
    numberOfInjectionRepeats);

bestLambdaAll = nan(numberOfCases,1);
bestLambdaQuality = nan(numberOfCases,1);
bestGateThreshold = nan(numberOfCases,1);

lambdaGrid = logspace(-4,4,17);

%% 6. Nested LOCO training and test-only signal corruption
for caseIndex = 1:numberOfCases

    testCase = caseList(caseIndex);

    testMask = caseID == testCase;
    trainMask = ~testMask;

    eligibleTestIndex = find( ...
        testMask & eligibleMask);

    fprintf("\nTraining outer fold for Case %d",testCase);
    fprintf("; eligible test records: %d\n", ...
        numel(eligibleTestIndex));

    % Tune both branches and the quality gate using only outer-training
    % cases. The selected clean-data policy is then frozen before the
    % held-out signals are corrupted.
    [~,~,~,bestLambdaAll(caseIndex), ...
        bestLambdaQuality(caseIndex), ...
        bestGateThreshold(caseIndex)] = ...
        groupedGatedRidgePrediction( ...
        XAllSensorsTime,XQualityAwareTime,originalSaturationRatio, ...
        y,caseID,trainMask,testMask,lambdaGrid,gateThresholdGrid);

    if isempty(eligibleTestIndex)
        continue;
    end

    for levelIndex = 1:numberOfLevels

        currentLevel = injectionLevels(levelIndex);

        fprintf("  Injected saturation: %3.0f%%\n", ...
            100*currentLevel);

        for repeatIndex = 1:numberOfInjectionRepeats

            % Begin from clean test inputs every time.
            XAllTest = ...
                XAllSensorsTime(eligibleTestIndex,:);

            XQualityTest = ...
                XQualityAwareTime(eligibleTestIndex,:);

            currentRatios = ...
                originalSaturationRatio(eligibleTestIndex);

            if currentLevel > 0

                for localRow = 1:numel(eligibleTestIndex)

                    globalRow = ...
                        eligibleTestIndex(localRow);

                    sourceIndex = ...
                        originalIndex(globalRow);

                    x = double( ...
                        mill(sourceIndex).smcDC(:));

                    numberOfPoints = numel(x);

                    centralStart = ...
                        floor(0.25*numberOfPoints)+1;

                    centralEnd = ...
                        floor(0.75*numberOfPoints);

                    xCentral = ...
                        x(centralStart:centralEnd);

                    centralLength = ...
                        numel(xCentral);

                    blockLength = min( ...
                        centralLength, ...
                        max(1,round( ...
                        currentLevel*centralLength)));

                    if blockLength >= centralLength
                        blockStart = 1;
                    else
                        % Reproducible random block position.
                        localSeed = ...
                            20260716 + ...
                            100000*repeatIndex + ...
                            1000*levelIndex + ...
                            sourceIndex;

                        localStream = RandStream( ...
                            "mt19937ar", ...
                            "Seed",localSeed);

                        blockStart = randi( ...
                            localStream, ...
                            centralLength-blockLength+1);
                    end

                    blockEnd = ...
                        blockStart+blockLength-1;

                    % Simulate an intermittent stuck-at-upper-rail fault.
                    xCorrupted = xCentral;

                    xCorrupted(blockStart:blockEnd) = ...
                        saturationRail;

                    corruptedFeatures = ...
                        calculateSignalFeaturesForInjection( ...
                        xCorrupted,Fs);

                    XAllTest( ...
                        localRow,smcDCInputColumns) = ...
                        corruptedFeatures;

                    currentRatios(localRow) = ...
                        mean(xCorrupted >= ...
                        saturationThreshold);
                end
            end

            currentPredAll = ...
                fitRidgeAndPredict( ...
                XAllSensorsTime(trainMask,:), ...
                y(trainMask),XAllTest, ...
                bestLambdaAll(caseIndex));

            currentPredQuality = ...
                fitRidgeAndPredict( ...
                XQualityAwareTime(trainMask,:), ...
                y(trainMask),XQualityTest, ...
                bestLambdaQuality(caseIndex));

            currentPredGated = currentPredAll;

            currentGateMask = ...
                currentRatios >= bestGateThreshold(caseIndex);

            currentPredGated(currentGateMask) = ...
                currentPredQuality(currentGateMask);

            predAllSensors( ...
                eligibleTestIndex,levelIndex,repeatIndex) = ...
                currentPredAll;

            predQualityAware( ...
                eligibleTestIndex,levelIndex,repeatIndex) = ...
                currentPredQuality;

            predQualityGated( ...
                eligibleTestIndex,levelIndex,repeatIndex) = ...
                currentPredGated;

            actualInjectedRatio( ...
                eligibleTestIndex,levelIndex,repeatIndex) = ...
                currentRatios;
        end
    end
end

%% 7. Calculate metrics for every repetition
modelNames = [ ...
    "AllSensorsTime"; ...
    "QualityAwareTime"; ...
    "QualityGatedTime"];

numberOfModels = numel(modelNames);

predictionArrays = { ...
    predAllSensors, ...
    predQualityAware, ...
    predQualityGated};

numberOfResultRows = ...
    numberOfLevels * ...
    numberOfInjectionRepeats * ...
    numberOfModels;

ResultLevel = nan(numberOfResultRows,1);
ResultRepeat = nan(numberOfResultRows,1);
ResultModel = strings(numberOfResultRows,1);
ActualMeanSaturationRatio = nan(numberOfResultRows,1);
MAE = nan(numberOfResultRows,1);
RMSE = nan(numberOfResultRows,1);
R2 = nan(numberOfResultRows,1);

resultRow = 0;

for levelIndex = 1:numberOfLevels
    for repeatIndex = 1:numberOfInjectionRepeats
        for modelIndex = 1:numberOfModels

            resultRow = resultRow+1;

            currentPrediction = ...
                predictionArrays{modelIndex}( ...
                :,levelIndex,repeatIndex);

            evaluationMask = ...
                eligibleMask & ...
                isfinite(currentPrediction);

            currentY = y(evaluationMask);
            currentPrediction = ...
                currentPrediction(evaluationMask);

            residual = currentPrediction-currentY;

            ResultLevel(resultRow) = ...
                injectionLevels(levelIndex);

            ResultRepeat(resultRow) = repeatIndex;
            ResultModel(resultRow) = modelNames(modelIndex);

            currentRatios = actualInjectedRatio( ...
                evaluationMask,levelIndex,repeatIndex);

            ActualMeanSaturationRatio(resultRow) = ...
                mean(currentRatios);

            MAE(resultRow) = mean(abs(residual));
            RMSE(resultRow) = sqrt(mean(residual.^2));

            R2(resultRow) = 1- ...
                sum(residual.^2) / ...
                sum((currentY-mean(currentY)).^2);
        end
    end
end

repeatResults = table( ...
    ResultLevel,ResultRepeat,ResultModel, ...
    ActualMeanSaturationRatio,MAE,RMSE,R2, ...
    'VariableNames', ...
    {'InjectedRatio','Repeat','Model', ...
     'ActualMeanSaturationRatio', ...
     'MAE','RMSE','R2'});

%% 8. Summarize repeated corruption results
numberOfSummaryRows = ...
    numberOfLevels*numberOfModels;

SummaryLevel = nan(numberOfSummaryRows,1);
SummaryModel = strings(numberOfSummaryRows,1);
MeanActualSaturationRatio = nan(numberOfSummaryRows,1);
MeanMAE = nan(numberOfSummaryRows,1);
StdMAE = nan(numberOfSummaryRows,1);
MeanRMSE = nan(numberOfSummaryRows,1);
StdRMSE = nan(numberOfSummaryRows,1);
MeanR2 = nan(numberOfSummaryRows,1);
StdR2 = nan(numberOfSummaryRows,1);

summaryRow = 0;

for levelIndex = 1:numberOfLevels
    for modelIndex = 1:numberOfModels

        summaryRow = summaryRow+1;

        mask = ...
            repeatResults.InjectedRatio == ...
            injectionLevels(levelIndex) & ...
            repeatResults.Model == modelNames(modelIndex);

        SummaryLevel(summaryRow) = ...
            injectionLevels(levelIndex);

        SummaryModel(summaryRow) = ...
            modelNames(modelIndex);

        MeanActualSaturationRatio(summaryRow) = ...
            mean(repeatResults.ActualMeanSaturationRatio(mask));

        MeanMAE(summaryRow) = ...
            mean(repeatResults.MAE(mask));

        StdMAE(summaryRow) = ...
            std(repeatResults.MAE(mask));

        MeanRMSE(summaryRow) = ...
            mean(repeatResults.RMSE(mask));

        StdRMSE(summaryRow) = ...
            std(repeatResults.RMSE(mask));

        MeanR2(summaryRow) = ...
            mean(repeatResults.R2(mask));

        StdR2(summaryRow) = ...
            std(repeatResults.R2(mask));
    end
end

summaryResults = table( ...
    SummaryLevel,SummaryModel, ...
    MeanActualSaturationRatio, ...
    MeanMAE,StdMAE,MeanRMSE,StdRMSE, ...
    MeanR2,StdR2, ...
    'VariableNames', ...
    {'InjectedRatio','Model', ...
     'MeanActualSaturationRatio', ...
     'MeanMAE','StdMAE', ...
     'MeanRMSE','StdRMSE', ...
     'MeanR2','StdR2'});

MAEIncreaseFromClean = ...
    nan(height(summaryResults),1);

for modelIndex = 1:numberOfModels

    cleanMask = ...
        summaryResults.Model == modelNames(modelIndex) & ...
        summaryResults.InjectedRatio == 0;

    cleanMAE = summaryResults.MeanMAE(cleanMask);

    modelMask = ...
        summaryResults.Model == modelNames(modelIndex);

    MAEIncreaseFromClean(modelMask) = ...
        summaryResults.MeanMAE(modelMask)-cleanMAE;
end

summaryResults.MAEIncreaseFromClean = ...
    MAEIncreaseFromClean;

fprintf("\n========== Saturation injection summary ==========\n");
disp(summaryResults);

%% 9. Plot robustness curves
fig = figure( ...
    "Color","w", ...
    "Position",[100 100 1350 560]);

tiledlayout(1,2, ...
    "TileSpacing","compact", ...
    "Padding","compact");

colors = lines(numberOfModels);

nexttile;
hold on;

for modelIndex = 1:numberOfModels

    mask = summaryResults.Model == modelNames(modelIndex);
    currentRows = summaryResults(mask,:);
    currentRows = sortrows(currentRows,"InjectedRatio");

    errorbar( ...
        100*currentRows.InjectedRatio, ...
        currentRows.MeanMAE, ...
        currentRows.StdMAE, ...
        "-o", ...
        "LineWidth",1.7, ...
        "MarkerSize",6, ...
        "Color",colors(modelIndex,:));
end

hold off;
grid on;
xlabel("Injected upper-rail ratio (%)");
ylabel("MAE");
title("Robustness to Artificial smcDC Saturation");
legend(modelNames,"Location","best");

nexttile;
hold on;

for modelIndex = 1:numberOfModels

    mask = summaryResults.Model == modelNames(modelIndex);
    currentRows = summaryResults(mask,:);
    currentRows = sortrows(currentRows,"InjectedRatio");

    errorbar( ...
        100*currentRows.InjectedRatio, ...
        currentRows.MeanR2, ...
        currentRows.StdR2, ...
        "-o", ...
        "LineWidth",1.7, ...
        "MarkerSize",6, ...
        "Color",colors(modelIndex,:));
end

hold off;
grid on;
xlabel("Injected upper-rail ratio (%)");
ylabel("R^2");
title("Coefficient of Determination under Corruption");
legend(modelNames,"Location","best");

axesHandles = findall(fig,"Type","axes");

for axisIndex = 1:numel(axesHandles)
    if ~isempty(axesHandles(axisIndex).Toolbar)
        axesHandles(axisIndex).Toolbar.Visible = "off";
    end
    disableDefaultInteractivity(axesHandles(axisIndex));
end

drawnow;

%% 10. Save results
writetable( ...
    repeatResults, ...
    fullfile(resultFolder, ...
    "saturation_injection_repeats.csv"));

writetable( ...
    summaryResults, ...
    fullfile(resultFolder, ...
    "saturation_injection_summary.csv"));

save( ...
    fullfile(resultFolder, ...
    "saturation_injection_results.mat"), ...
    "repeatResults","summaryResults", ...
    "predAllSensors","predQualityAware", ...
    "predQualityGated", ...
    "actualInjectedRatio", ...
    "bestLambdaAll","bestLambdaQuality", ...
    "bestGateThreshold","gateThresholdGrid", ...
    "cleanEligibilityThreshold", ...
    "eligibleMask","injectionLevels");

exportgraphics( ...
    fig, ...
    fullfile(resultFolder, ...
    "saturation_injection_robustness.png"), ...
    "Resolution",300);

fprintf("\nSaved saturation-injection results to:\n%s\n", ...
    resultFolder);


%% Local function: identical feature definitions used previously
function features = ...
    calculateSignalFeaturesForInjection(x,Fs)

x = double(x(:));

featureMean = mean(x);
featureRMS = rms(x);
featureStd = std(x);
featurePeakToPeak = max(x)-min(x);

xDetrended = detrend(x);

featureSkewness = skewness(xDetrended);
featureKurtosis = kurtosis(xDetrended);

detrendedRMS = rms(xDetrended);

featureCrestFactor = ...
    max(abs(xDetrended))/max(detrendedRMS,eps);

windowLength = min(512,numel(xDetrended));
analysisWindow = hamming(windowLength);
overlapLength = floor(windowLength/2);
nfft = max(1024,2^nextpow2(windowLength));

[Pxx,f] = pwelch( ...
    xDetrended,analysisWindow, ...
    overlapLength,nfft,Fs);

totalPower = sum(Pxx);

if totalPower <= eps
    normalizedPower = ...
        ones(size(Pxx))/numel(Pxx);
else
    normalizedPower = Pxx/totalPower;
end

featureMeanFrequency = ...
    sum(f.*normalizedPower);

cumulativePower = cumsum(normalizedPower);

medianIndex = find( ...
    cumulativePower >= 0.5,1,"first");

featureMedianFrequency = f(medianIndex);

featureSpectralEntropy = ...
    -sum(normalizedPower.* ...
    log2(normalizedPower+eps)) / ...
    log2(numel(normalizedPower));

lowMask = f >= 0 & f < 20;
midMask = f >= 20 & f < 60;
highMask = f >= 60 & f <= Fs/2;

featureLowBandRatio = ...
    sum(normalizedPower(lowMask));

featureMidBandRatio = ...
    sum(normalizedPower(midMask));

featureHighBandRatio = ...
    sum(normalizedPower(highMask));

features = [ ...
    featureMean,featureRMS,featureStd, ...
    featurePeakToPeak,featureSkewness, ...
    featureKurtosis,featureCrestFactor, ...
    featureMeanFrequency, ...
    featureMedianFrequency, ...
    featureSpectralEntropy, ...
    featureLowBandRatio, ...
    featureMidBandRatio, ...
    featureHighBandRatio];

end
