paperRoot = fileparts(mfilename('fullpath'));
clear;
clc;
close all;

%% 1. 读取质量感知特征表
resultFolder = ...
    fullfile(paperRoot, 'mill', 'results');

loadedData = load( ...
    fullfile(resultFolder, ...
    "quality_aware_features.mat"));

T = loadedData.qualityAwareTable;

%% 2. 基础信息
y = T.VB;
caseID = T.CaseID;
runID = T.RunID;
originalIndex = T.OriginalIndex;

caseList = unique(caseID);
nSamples = height(T);

%% 3. 确定变量名称
allVariableNames = ...
    string(T.Properties.VariableNames);

% 原始78个传感器特征位于第8～85列
sensorVariableNames = ...
    allVariableNames(8:85);

smcDCMask = startsWith( ...
    sensorVariableNames, ...
    "smcDC_");

otherSensorVariableNames = ...
    sensorVariableNames(~smcDCMask);

%% 4. 构造三种输入
XProcess = T{:,{'DOC','Feed','Material'}};

% 方案1：全部六路传感器
XAllSensors = [ ...
    XProcess, ...
    T{:,cellstr(sensorVariableNames)}];

% 方案2：完全移除smcDC
XNoSmcDC = [ ...
    XProcess, ...
    T{:,cellstr(otherSensorVariableNames)}];

% 方案3：移除smcDC常规特征，只保留饱和比例
XQualityAware = [ ...
    XProcess, ...
    T{:,cellstr(otherSensorVariableNames)}, ...
    T.smcDC_SaturationRatio];

modelNames = [ ...
    "AllSensors", ...
    "NoSmcDC", ...
    "QualityAware"];

XSets = { ...
    XAllSensors, ...
    XNoSmcDC, ...
    XQualityAware};

nModels = numel(modelNames);

fprintf("========== 三种输入维度 ==========\n");
fprintf("AllSensors：%d\n",size(XAllSensors,2));
fprintf("NoSmcDC：%d\n",size(XNoSmcDC,2));
fprintf("QualityAware：%d\n",size(XQualityAware,2));

%% 5. 初始化结果
predictionMatrix = nan(nSamples,nModels);
bestLambda = nan(numel(caseList),nModels);

lambdaGrid = logspace(-4,4,17);

%% 6. 留一案例外层验证
for k = 1:numel(caseList)

    testCase = caseList(k);

    testMask = caseID == testCase;
    trainMask = ~testMask;

    fprintf( ...
        "\n正在测试Case %d：训练%d条，测试%d条\n", ...
        testCase,sum(trainMask),sum(testMask));

    for m = 1:nModels

        fprintf("  模型：%s\n",modelNames(m));

        [predictionMatrix(testMask,m), ...
            bestLambda(k,m)] = ...
            groupedRidgePrediction( ...
            XSets{m}, ...
            y, ...
            caseID, ...
            trainMask, ...
            testMask, ...
            lambdaGrid);
    end
end

%% 7. 总体指标
MAE = nan(nModels,1);
RMSE = nan(nModels,1);
R2 = nan(nModels,1);

for m = 1:nModels

    [MAE(m),RMSE(m),R2(m)] = ...
        calculateRegressionMetrics( ...
        y,predictionMatrix(:,m));
end

overallResults = table( ...
    modelNames',MAE,RMSE,R2, ...
    'VariableNames', ...
    {'Strategy','MAE','RMSE','R2'});

fprintf("\n========== 三种策略总体结果 ==========\n");
disp(overallResults);

%% 8. 相对于AllSensors的变化
MAEChangePercent = ...
    100*(MAE-MAE(1))/MAE(1);

RMSEChangePercent = ...
    100*(RMSE-RMSE(1))/RMSE(1);

comparisonResults = table( ...
    modelNames', ...
    MAEChangePercent, ...
    RMSEChangePercent, ...
    'VariableNames', ...
    {'Strategy','MAEChangePercent', ...
     'RMSEChangePercent'});

fprintf("\n========== 相对于AllSensors的变化 ==========\n");
fprintf("负数表示误差下降，性能改善。\n");
disp(comparisonResults);

%% 9. 每个案例的MAE
caseSampleCount = nan(numel(caseList),1);
caseMAE = nan(numel(caseList),nModels);

for k = 1:numel(caseList)

    mask = caseID == caseList(k);

    caseSampleCount(k) = sum(mask);

    for m = 1:nModels
        caseMAE(k,m) = mean( ...
            abs(y(mask)- ...
            predictionMatrix(mask,m)));
    end
end

caseResults = table( ...
    caseList, ...
    caseSampleCount, ...
    caseMAE(:,1), ...
    caseMAE(:,2), ...
    caseMAE(:,3), ...
    'VariableNames', ...
    {'CaseID','SampleCount', ...
     'AllSensorsMAE', ...
     'NoSmcDCMAE', ...
     'QualityAwareMAE'});

fprintf("\n========== 每个案例的MAE ==========\n");
disp(caseResults);

%% 10. 不同磨损区间的性能
wearGroupNames = [ ...
    "VB < 0.2", ...
    "0.2 <= VB < 0.4", ...
    "VB >= 0.4"];

wearMasks = { ...
    y < 0.2, ...
    y >= 0.2 & y < 0.4, ...
    y >= 0.4};

resultRows = nModels*numel(wearGroupNames);

Strategy = strings(resultRows,1);
WearGroup = strings(resultRows,1);
SampleCount = nan(resultRows,1);
GroupMAE = nan(resultRows,1);
GroupRMSE = nan(resultRows,1);
MeanResidual = nan(resultRows,1);

rowCounter = 0;

for m = 1:nModels

    for g = 1:numel(wearGroupNames)

        rowCounter = rowCounter+1;

        mask = wearMasks{g};

        residual = ...
            predictionMatrix(mask,m)-y(mask);

        Strategy(rowCounter) = modelNames(m);
        WearGroup(rowCounter) = ...
            wearGroupNames(g);

        SampleCount(rowCounter) = sum(mask);
        GroupMAE(rowCounter) = ...
            mean(abs(residual));

        GroupRMSE(rowCounter) = ...
            sqrt(mean(residual.^2));

        MeanResidual(rowCounter) = ...
            mean(residual);
    end
end

wearGroupResults = table( ...
    Strategy,WearGroup,SampleCount, ...
    GroupMAE,GroupRMSE,MeanResidual);

fprintf("\n========== 不同磨损区间的结果 ==========\n");
disp(wearGroupResults);

%% 11. 检查OriginalIndex 109
targetMask = originalIndex == 109;

index109Results = table( ...
    originalIndex(targetMask), ...
    caseID(targetMask), ...
    runID(targetMask), ...
    y(targetMask), ...
    predictionMatrix(targetMask,1), ...
    predictionMatrix(targetMask,2), ...
    predictionMatrix(targetMask,3), ...
    'VariableNames', ...
    {'OriginalIndex','CaseID','RunID', ...
     'ActualVB','AllSensorsPrediction', ...
     'NoSmcDCPrediction', ...
     'QualityAwarePrediction'});

fprintf("\n========== OriginalIndex 109对比 ==========\n");
disp(index109Results);

%% 12. 保存逐样本预测
predictionTable = table( ...
    originalIndex,caseID,runID,y, ...
    predictionMatrix(:,1), ...
    predictionMatrix(:,2), ...
    predictionMatrix(:,3), ...
    'VariableNames', ...
    {'OriginalIndex','CaseID','RunID', ...
     'ActualVB','PredAllSensors', ...
     'PredNoSmcDC','PredQualityAware'});

%% 13. 真实值与预测值图
fig1 = figure( ...
    "Color","w", ...
    "Position",[100 100 1500 500]);

tiledlayout(1,3, ...
    "TileSpacing","compact", ...
    "Padding","compact");

plotMinimum = min( ...
    [y;predictionMatrix(:)]);

plotMaximum = max( ...
    [y;predictionMatrix(:)]);

for m = 1:nModels

    nexttile;

    scatter( ...
        y,predictionMatrix(:,m), ...
        38,caseID,"filled");

    hold on;

    plot( ...
        [plotMinimum plotMaximum], ...
        [plotMinimum plotMaximum], ...
        "k--","LineWidth",1.2);

    hold off;
    grid on;
    axis square;

    xlim([plotMinimum plotMaximum]);
    ylim([plotMinimum plotMaximum]);

    xlabel("Actual VB");
    ylabel("Predicted VB");

    title( ...
        modelNames(m)+ ...
        ", MAE="+sprintf("%.3f",MAE(m))+ ...
        ", R^2="+sprintf("%.3f",R2(m)));

    colorbar;
end

sgtitle( ...
    "Sensor-Quality Strategy Comparison");

%% 14. 每个案例的MAE图
fig2 = figure( ...
    "Color","w", ...
    "Position",[100 100 1400 650]);

bar(caseList,caseMAE,"grouped");

grid on;
xlabel("Held-out case");
ylabel("MAE");
title("MAE for Each Held-Out Case");
legend(modelNames,"Location","northwest");

%% 15. 保存结果
writetable( ...
    overallResults, ...
    fullfile(resultFolder, ...
    "quality_strategy_overall.csv"));

writetable( ...
    comparisonResults, ...
    fullfile(resultFolder, ...
    "quality_strategy_changes.csv"));

writetable( ...
    caseResults, ...
    fullfile(resultFolder, ...
    "quality_strategy_cases.csv"));

writetable( ...
    wearGroupResults, ...
    fullfile(resultFolder, ...
    "quality_strategy_wear_groups.csv"));

writetable( ...
    predictionTable, ...
    fullfile(resultFolder, ...
    "quality_strategy_predictions.csv"));

save( ...
    fullfile(resultFolder, ...
    "quality_strategy_results.mat"), ...
    "overallResults", ...
    "comparisonResults", ...
    "caseResults", ...
    "wearGroupResults", ...
    "predictionTable", ...
    "bestLambda");

exportgraphics( ...
    fig1, ...
    fullfile(resultFolder, ...
    "quality_strategy_scatter.png"), ...
    "Resolution",300);

exportgraphics( ...
    fig2, ...
    fullfile(resultFolder, ...
    "quality_strategy_case_MAE.png"), ...
    "Resolution",300);

%% 局部函数1：分组岭回归
function [testPrediction,bestLambda] = ...
    groupedRidgePrediction( ...
    X,y,groupID,outerTrainMask, ...
    outerTestMask,lambdaGrid)

    trainingCases = unique( ...
        groupID(outerTrainMask));

    validationMAE = nan( ...
        numel(lambdaGrid),1);

    for lambdaIndex = 1:numel(lambdaGrid)

        currentLambda = ...
            lambdaGrid(lambdaIndex);

        validationPrediction = ...
            nan(size(y));

        for caseIndex = 1:numel(trainingCases)

            validationCase = ...
                trainingCases(caseIndex);

            innerValidationMask = ...
                outerTrainMask & ...
                groupID == validationCase;

            innerTrainingMask = ...
                outerTrainMask & ...
                groupID ~= validationCase;

            validationPrediction( ...
                innerValidationMask) = ...
                fitRidgeAndPredict( ...
                X(innerTrainingMask,:), ...
                y(innerTrainingMask), ...
                X(innerValidationMask,:), ...
                currentLambda);
        end

        validationMAE(lambdaIndex) = ...
            mean(abs( ...
            y(outerTrainMask)- ...
            validationPrediction(outerTrainMask)));
    end

    [~,bestIndex] = min(validationMAE);
    bestLambda = lambdaGrid(bestIndex);

    testPrediction = fitRidgeAndPredict( ...
        X(outerTrainMask,:), ...
        y(outerTrainMask), ...
        X(outerTestMask,:), ...
        bestLambda);
end

%% 局部函数2：拟合岭回归
function yPrediction = ...
    fitRidgeAndPredict( ...
    XTrain,yTrain,XTest,lambda)

    featureMean = mean(XTrain,1);
    featureStd = std(XTrain,[],1);

    keepFeature = ...
        isfinite(featureStd) & ...
        featureStd > 1e-12;

    XTrain = XTrain(:,keepFeature);
    XTest = XTest(:,keepFeature);

    featureMean = featureMean(keepFeature);
    featureStd = featureStd(keepFeature);

    XTrainZ = ...
        (XTrain-featureMean)./featureStd;

    XTestZ = ...
        (XTest-featureMean)./featureStd;

    responseMean = mean(yTrain);
    yCentered = yTrain-responseMean;

    nFeatures = size(XTrainZ,2);

    beta = ( ...
        XTrainZ'*XTrainZ + ...
        lambda*eye(nFeatures)) \ ...
        (XTrainZ'*yCentered);

    yPrediction = ...
        responseMean+XTestZ*beta;
end

%% 局部函数3：回归指标
function [MAE,RMSE,R2] = ...
    calculateRegressionMetrics( ...
    actual,predicted)

    validMask = ...
        isfinite(actual) & ...
        isfinite(predicted);

    actual = actual(validMask);
    predicted = predicted(validMask);

    residual = actual-predicted;

    MAE = mean(abs(residual));
    RMSE = sqrt(mean(residual.^2));

    R2 = 1- ...
        sum(residual.^2)/ ...
        sum((actual-mean(actual)).^2);
end