paperRoot = fileparts(mfilename('fullpath'));
clear;
clc;
close all;

rng(2026);

%% 1. 读取数据
resultFolder = ...
    fullfile(paperRoot, 'mill', 'results');

qualityData = load( ...
    fullfile(resultFolder, ...
    "quality_aware_features.mat"));

gatedData = load( ...
    fullfile(resultFolder, ...
    "gated_results.mat"));

T = qualityData.qualityAwareTable;
ridgePredictionTable = ...
    gatedData.gatedPredictionTable;

assert( ...
    isequal( ...
    T.OriginalIndex, ...
    ridgePredictionTable.OriginalIndex), ...
    "数据行顺序不一致");

%% 2. 基本信息
y = T.VB;
caseID = T.CaseID;
runID = T.RunID;
originalIndex = T.OriginalIndex;
saturationRatio = T.smcDC_SaturationRatio;

caseList = unique(caseID);
nSamples = height(T);

%% 3. 建立AllSensors和QualityAware输入
allVariableNames = ...
    string(T.Properties.VariableNames);

sensorVariableNames = ...
    allVariableNames(8:85);

smcDCMask = startsWith( ...
    sensorVariableNames, ...
    "smcDC_");

otherSensorNames = ...
    sensorVariableNames(~smcDCMask);

XProcess = T{:,{'DOC','Feed','Material'}};

XAllSensors = [ ...
    XProcess, ...
    T{:,cellstr(sensorVariableNames)}];

XQualityAware = [ ...
    XProcess, ...
    T{:,cellstr(otherSensorNames)}];

XSets = {XAllSensors,XQualityAware};
branchNames = ["AllSensors","QualityAware"];

%% 4. SVR超参数网格
boxConstraintGrid = [1 10 100];
kernelScaleGrid = [2 5 10 20];

% 暂时固定Epsilon，避免搜索规模过大
epsilonValue = 0.05;

%% 5. 外层预测
predSVRAll = nan(nSamples,1);
predSVRQuality = nan(nSamples,1);

predictionBranches = { ...
    predSVRAll, ...
    predSVRQuality};

bestBoxConstraint = nan( ...
    numel(caseList),2);

bestKernelScale = nan( ...
    numel(caseList),2);

for k = 1:numel(caseList)

    testCase = caseList(k);

    testMask = caseID == testCase;
    trainMask = ~testMask;

    fprintf( ...
        "\n正在测试Case %d：训练%d条，测试%d条\n", ...
        testCase,sum(trainMask),sum(testMask));

    for branch = 1:2

        fprintf("  SVR分支：%s\n", ...
            branchNames(branch));

        [currentPrediction, ...
            selectedC,selectedScale] = ...
            groupedSVRPrediction( ...
            XSets{branch}, ...
            y,caseID, ...
            trainMask,testMask, ...
            boxConstraintGrid, ...
            kernelScaleGrid, ...
            epsilonValue);

        predictionBranches{branch}(testMask) = ...
            currentPrediction;

        bestBoxConstraint(k,branch) = ...
            selectedC;

        bestKernelScale(k,branch) = ...
            selectedScale;
    end
end

predSVRAll = predictionBranches{1};
predSVRQuality = predictionBranches{2};

%% 6. 质量门控
saturationMask = saturationRatio >= 0.01;

predSVRGated = predSVRAll;
predSVRGated(saturationMask) = ...
    predSVRQuality(saturationMask);

% 已有岭回归门控预测
predRidgeGated = ...
    ridgePredictionTable.PredGated1;

%% 7. 总体比较
modelNames = [ ...
    "RidgeGated", ...
    "SVRAllSensors", ...
    "SVRQualityAware", ...
    "SVRGated"];

predictionMatrix = [ ...
    predRidgeGated, ...
    predSVRAll, ...
    predSVRQuality, ...
    predSVRGated];

nModels = numel(modelNames);

MAE = nan(nModels,1);
RMSE = nan(nModels,1);
R2 = nan(nModels,1);
P95AbsoluteError = nan(nModels,1);
MaximumAbsoluteError = nan(nModels,1);

for m = 1:nModels

    residual = ...
        predictionMatrix(:,m)-y;

    absoluteError = abs(residual);

    MAE(m) = mean(absoluteError);
    RMSE(m) = sqrt(mean(residual.^2));

    R2(m) = 1- ...
        sum(residual.^2)/ ...
        sum((y-mean(y)).^2);

    P95AbsoluteError(m) = ...
        prctile(absoluteError,95);

    MaximumAbsoluteError(m) = ...
        max(absoluteError);
end

overallResults = table( ...
    modelNames',MAE,RMSE,R2, ...
    P95AbsoluteError, ...
    MaximumAbsoluteError, ...
    'VariableNames', ...
    {'Model','MAE','RMSE','R2', ...
     'P95AbsoluteError', ...
     'MaximumAbsoluteError'});

fprintf("\n========== SVR总体结果 ==========\n");
disp(overallResults);

%% 8. 每个案例的MAE
caseMAE = nan(numel(caseList),nModels);
caseSampleCount = nan(numel(caseList),1);

for k = 1:numel(caseList)

    mask = caseID == caseList(k);
    caseSampleCount(k) = sum(mask);

    for m = 1:nModels
        caseMAE(k,m) = mean( ...
            abs(predictionMatrix(mask,m)-y(mask)));
    end
end

caseResults = table( ...
    caseList,caseSampleCount, ...
    caseMAE(:,1), ...
    caseMAE(:,2), ...
    caseMAE(:,3), ...
    caseMAE(:,4), ...
    'VariableNames', ...
    {'CaseID','SampleCount', ...
     'RidgeGatedMAE', ...
     'SVRAllMAE', ...
     'SVRQualityMAE', ...
     'SVRGatedMAE'});

fprintf("\n========== 每个案例SVR结果 ==========\n");
disp(caseResults);

%% 9. 找出每个模型最大误差记录
WorstOriginalIndex = nan(nModels,1);
WorstCaseID = nan(nModels,1);
WorstRunID = nan(nModels,1);
WorstActualVB = nan(nModels,1);
WorstPredictedVB = nan(nModels,1);
WorstAbsoluteError = nan(nModels,1);

for m = 1:nModels

    absoluteError = abs( ...
        predictionMatrix(:,m)-y);

    [WorstAbsoluteError(m),worstIndex] = ...
        max(absoluteError);

    WorstOriginalIndex(m) = ...
        originalIndex(worstIndex);

    WorstCaseID(m) = caseID(worstIndex);
    WorstRunID(m) = runID(worstIndex);
    WorstActualVB(m) = y(worstIndex);

    WorstPredictedVB(m) = ...
        predictionMatrix(worstIndex,m);
end

worstResults = table( ...
    modelNames', ...
    WorstOriginalIndex, ...
    WorstCaseID, ...
    WorstRunID, ...
    WorstActualVB, ...
    WorstPredictedVB, ...
    WorstAbsoluteError, ...
    'VariableNames', ...
    {'Model','OriginalIndex','CaseID', ...
     'RunID','ActualVB','PredictedVB', ...
     'AbsoluteError'});

fprintf("\n========== 每个模型的最大误差 ==========\n");
disp(worstResults);

%% 10. 检查OriginalIndex 109
targetMask = originalIndex == 109;

targetResults = table( ...
    originalIndex(targetMask), ...
    y(targetMask), ...
    saturationRatio(targetMask), ...
    predRidgeGated(targetMask), ...
    predSVRAll(targetMask), ...
    predSVRQuality(targetMask), ...
    predSVRGated(targetMask), ...
    'VariableNames', ...
    {'OriginalIndex','ActualVB', ...
     'SaturationRatio','RidgeGated', ...
     'SVRAll','SVRQuality','SVRGated'});

fprintf("\n========== OriginalIndex 109 ==========\n");
disp(targetResults);

%% 11. 保存逐样本预测
predictionTable = table( ...
    originalIndex,caseID,runID,y, ...
    saturationRatio, ...
    predRidgeGated,predSVRAll, ...
    predSVRQuality,predSVRGated, ...
    'VariableNames', ...
    {'OriginalIndex','CaseID','RunID', ...
     'ActualVB','SaturationRatio', ...
     'PredRidgeGated','PredSVRAll', ...
     'PredSVRQuality','PredSVRGated'});

%% 12. 绘图
fig1 = figure( ...
    "Color","w", ...
    "Position",[100 100 1300 1000]);

tiledlayout(2,2, ...
    "TileSpacing","compact", ...
    "Padding","compact");

plotMin = min([y;predictionMatrix(:)]);
plotMax = max([y;predictionMatrix(:)]);

for m = 1:nModels

    nexttile;

    scatter( ...
        y,predictionMatrix(:,m), ...
        38,caseID,"filled");

    hold on;

    plot( ...
        [plotMin plotMax], ...
        [plotMin plotMax], ...
        "k--","LineWidth",1.2);

    hold off;
    grid on;
    axis square;

    xlim([plotMin plotMax]);
    ylim([plotMin plotMax]);

    xlabel("Actual VB");
    ylabel("Predicted VB");

    title( ...
        modelNames(m)+ ...
        ", MAE="+sprintf("%.3f",MAE(m))+ ...
        ", R^2="+sprintf("%.3f",R2(m)));

    colorbar;
end

sgtitle("Grouped SVR and Quality-Gated SVR");

fig2 = figure( ...
    "Color","w", ...
    "Position",[100 100 1400 650]);

bar(caseList,caseMAE,"grouped");

grid on;
xlabel("Held-out case");
ylabel("MAE");
title("Case-Level Comparison of Ridge and SVR");
legend(modelNames,"Location","northwest");

%% 13. 保存
writetable( ...
    overallResults, ...
    fullfile(resultFolder, ...
    "svr_overall_results.csv"));

writetable( ...
    caseResults, ...
    fullfile(resultFolder, ...
    "svr_case_results.csv"));

writetable( ...
    worstResults, ...
    fullfile(resultFolder, ...
    "svr_worst_results.csv"));

writetable( ...
    predictionTable, ...
    fullfile(resultFolder, ...
    "svr_predictions.csv"));

save( ...
    fullfile(resultFolder, ...
    "svr_results.mat"), ...
    "overallResults","caseResults", ...
    "worstResults","predictionTable", ...
    "bestBoxConstraint", ...
    "bestKernelScale", ...
    "boxConstraintGrid", ...
    "kernelScaleGrid", ...
    "epsilonValue");

exportgraphics( ...
    fig1, ...
    fullfile(resultFolder, ...
    "svr_scatter_results.png"), ...
    "Resolution",300);

exportgraphics( ...
    fig2, ...
    fullfile(resultFolder, ...
    "svr_case_MAE.png"), ...
    "Resolution",300);

%% 局部函数1：分组选择SVR参数
function [testPrediction,bestC,bestScale] = ...
    groupedSVRPrediction( ...
    X,y,groupID,outerTrainMask, ...
    outerTestMask,CGrid,scaleGrid, ...
    epsilonValue)

    trainingCases = unique( ...
        groupID(outerTrainMask));

    validationMAE = nan( ...
        numel(CGrid),numel(scaleGrid));

    for cIndex = 1:numel(CGrid)

        for scaleIndex = 1:numel(scaleGrid)

            validationPrediction = ...
                nan(size(y));

            for caseIndex = 1:numel(trainingCases)

                validationCase = ...
                    trainingCases(caseIndex);

                innerValidationMask = ...
                    outerTrainMask & ...
                    groupID == validationCase;

                innerTrainingMask = ...
                    outerTrainMask & ...
                    groupID ~= validationCase;

                validationPrediction( ...
                    innerValidationMask) = ...
                    fitSVRAndPredict( ...
                    X(innerTrainingMask,:), ...
                    y(innerTrainingMask), ...
                    X(innerValidationMask,:), ...
                    CGrid(cIndex), ...
                    scaleGrid(scaleIndex), ...
                    epsilonValue);
            end

            validationMAE(cIndex,scaleIndex) = ...
                mean(abs( ...
                y(outerTrainMask)- ...
                validationPrediction(outerTrainMask)));
        end
    end

    [~,linearIndex] = min( ...
        validationMAE(:));

    [bestCIndex,bestScaleIndex] = ...
        ind2sub( ...
        size(validationMAE), ...
        linearIndex);

    bestC = CGrid(bestCIndex);
    bestScale = ...
        scaleGrid(bestScaleIndex);

    testPrediction = fitSVRAndPredict( ...
        X(outerTrainMask,:), ...
        y(outerTrainMask), ...
        X(outerTestMask,:), ...
        bestC,bestScale,epsilonValue);
end

%% 局部函数2：训练并预测SVR
function prediction = fitSVRAndPredict( ...
    XTrain,yTrain,XTest, ...
    boxConstraint,kernelScale, ...
    epsilonValue)

    featureMean = mean(XTrain,1);
    featureStd = std(XTrain,[],1);

    keepFeature = ...
        isfinite(featureStd) & ...
        featureStd > 1e-12;

    XTrain = XTrain(:,keepFeature);
    XTest = XTest(:,keepFeature);

    featureMean = ...
        featureMean(keepFeature);

    featureStd = ...
        featureStd(keepFeature);

    XTrainZ = ...
        (XTrain-featureMean)./featureStd;

    XTestZ = ...
        (XTest-featureMean)./featureStd;

    model = fitrsvm( ...
        XTrainZ,yTrain, ...
        "KernelFunction","gaussian", ...
        "KernelScale",kernelScale, ...
        "BoxConstraint",boxConstraint, ...
        "Epsilon",epsilonValue, ...
        "Standardize",false, ...
        "RemoveDuplicates",true);

    prediction = predict(model,XTestZ);
end
