clear; clc; close all;

paperRoot = fileparts(mfilename('fullpath'));
mainDir = fullfile(paperRoot,'mill','results');
outDir = fullfile(paperRoot,'additional_validation_results');
externalDir = fullfile(paperRoot,'external_validation_results');
faultDir = fullfile(paperRoot,'multifault_robustness_results');
if ~exist(outDir,'dir'), mkdir(outDir); end

mainModels = readtable(fullfile(mainDir,'paper_model_comparison.csv'), ...
    'VariableNamingRule','preserve','TextType','string');
mainFindings = readtable(fullfile(mainDir,'paper_key_findings.csv'), ...
    'VariableNamingRule','preserve','TextType','string');
permSummary = readtable(fullfile(outDir,'time_permutation_summary.csv'), ...
    'VariableNamingRule','preserve','TextType','string');
uncertainty = readtable(fullfile(outDir,'time_uncertainty_summary.csv'), ...
    'VariableNamingRule','preserve','TextType','string');
highWear = readtable(fullfile(outDir,'high_wear_bands.csv'), ...
    'VariableNamingRule','preserve','TextType','string');
alerts = readtable(fullfile(outDir,'critical_wear_classification.csv'), ...
    'VariableNamingRule','preserve','TextType','string');
strongModels = readtable(fullfile(outDir,'pls_gpr_overall.csv'), ...
    'VariableNamingRule','preserve','TextType','string');
strongStats = readtable(fullfile(outDir,'pls_gpr_statistics.csv'), ...
    'VariableNamingRule','preserve','TextType','string');
externalSummary = readtable(fullfile(externalDir,'external_validation_summary.csv'), ...
    'VariableNamingRule','preserve','TextType','string');
externalStats = readtable(fullfile(externalDir,'external_validation_statistics.csv'), ...
    'VariableNamingRule','preserve','TextType','string');
faultStats = readtable(fullfile(faultDir,'multifault_statistics.csv'), ...
    'VariableNamingRule','preserve','TextType','string');
cleanGate = readtable(fullfile(faultDir,'multifault_clean_gating_summary.csv'), ...
    'VariableNamingRule','preserve','TextType','string');

%% Master evidence table
evidenceArea = strings(0,1); endpoint = strings(0,1); value = zeros(0,1);
unit = strings(0,1); independentUnit = strings(0,1); interpretation = strings(0,1);
add = @(area,name,val,u,iu,note) struct('area',area,'name',name, ...
    'value',val,'unit',u,'iu',iu,'note',note);
rows = repmat(add("","",0,"","",""),0,1);

primary = mainModels(mainModels.IsProposedModel==1,:);
conventional = mainModels(mainModels.Model=="Process + sensor ridge",:);
rows(end+1)=add("Primary grouped validation","MAE",primary.MAE,"VB", ...
    "146 records nested in 16 cases","Strict nested leave-one-case-out");
rows(end+1)=add("Primary grouped validation","RMSE",primary.RMSE,"VB", ...
    "146 records nested in 16 cases","Strict nested leave-one-case-out");
rows(end+1)=add("Primary grouped validation","R2",primary.R2,"dimensionless", ...
    "146 records nested in 16 cases","Strict nested leave-one-case-out");
rows(end+1)=add("Primary grouped validation","MAE improvement vs conventional", ...
    100*(conventional.MAE-primary.MAE)/conventional.MAE,"percent", ...
    "16 paired cases","Proposed model has lower pooled MAE");

rows(end+1)=add("Time shortcut falsification","Permutation empirical p", ...
    permSummary.EmpiricalP,"p-value","100 case-wise permutations", ...
    "Elapsed-time ordering contains predictive information beyond case trend");
rows(end+1)=add("Time shortcut falsification","Observed better than permutations", ...
    permSummary.ObservedBetterThanPercent,"percent","100 case-wise permutations", ...
    "Observed chronology outperformed every permuted chronology");

missingRow = uncertainty(uncertainty.Scenario=="Missing25Percent",:);
rows(end+1)=add("Time measurement robustness","MAE increase with 25% missing time", ...
    missingRow.MAEChangePercent,"percent","16 cases; 50 repeated corruptions", ...
    "Outer-training-median imputation causes a small degradation");

highRow = highWear(highWear.Model=="PrimaryTimeGated" & ...
    highWear.WearBand=="VB >= 0.4",:);
alertRow = alerts(alerts.Model=="PrimaryTimeGated" & alerts.AlertThreshold==0.4,:);
rows(end+1)=add("High-wear safety","MAE for VB >= 0.4",highRow.MAE,"VB", ...
    "52 records nested in 15 evaluable cases","High wear remains the main error regime");
rows(end+1)=add("High-wear safety","Sensitivity at VB = 0.4", ...
    100*alertRow.Sensitivity,"percent","52 positive and 94 negative records", ...
    "Critical-wear alert sensitivity");
rows(end+1)=add("High-wear safety","Balanced accuracy at VB = 0.4", ...
    100*alertRow.BalancedAccuracy,"percent","146 records nested in 16 cases", ...
    "Threshold analysis is secondary to continuous regression");

gprRow = strongModels(strongModels.modelNames=="GPRQualityAwareTime",:);
gprStat = strongStats(strongStats.Comparator=="GPRQualityAwareTime",:);
rows(end+1)=add("Strong baseline","Quality-aware GPR MAE",gprRow.MAE,"VB", ...
    "146 records nested in 16 cases","Primary ridge retains lower pooled MAE");
rows(end+1)=add("Strong baseline","Quality-aware GPR R2",gprRow.R2,"dimensionless", ...
    "146 records nested in 16 cases","GPR is stronger on squared-error metrics");
rows(end+1)=add("Strong baseline","GPR minus primary case-MAE difference", ...
    gprStat.MeanCaseMAEDifferenceFromPrimary,"VB","16 paired cases", ...
    "Difference is not statistically conclusive");

for ds = ["NUAA","PHM2010"]
    ext = externalSummary(externalSummary.Dataset==ds & ...
        externalSummary.Model=="SensorTimeRidge",:);
    if ds=="NUAA"
        extUnit="9 experiments";
    else
        extUnit="3 cutters";
    end
    rows(end+1)=add("External clean validation",ds+" sensor-time ridge MAE", ...
        ext.MAE,"wear label units",extUnit, ...
        "Clean-data transportability; time is not universally beneficial");
end

combinedFault = faultStats(faultStats.Dataset=="Combined",:);
rows(end+1)=add("Cross-dataset fault robustness", ...
    "Relative MAE improvement of automatic gating", ...
    combinedFault.RelativeMAEImprovementPercent,"percent", ...
    "12 independent experiments/cutters", ...
    "11 of 12 independent units improved under multi-sensor multi-fault corruption");
rows(end+1)=add("Cross-dataset fault robustness","Holm-adjusted p", ...
    combinedFault.HolmAdjustedP,"p-value","12 paired independent units", ...
    "Significant after controlling the three dataset-level comparisons");
rows(end+1)=add("Cross-dataset fault robustness","Cluster-bootstrap CI lower", ...
    combinedFault.BootstrapCILower,"relative MAE","12 experiment clusters", ...
    "CI for automatic minus full-sensor relative MAE");
rows(end+1)=add("Cross-dataset fault robustness","Cluster-bootstrap CI upper", ...
    combinedFault.BootstrapCIUpper,"relative MAE","12 experiment clusters", ...
    "CI for automatic minus full-sensor relative MAE");

for i=1:numel(rows)
    evidenceArea(i,1)=rows(i).area; endpoint(i,1)=rows(i).name;
    value(i,1)=rows(i).value; unit(i,1)=rows(i).unit;
    independentUnit(i,1)=rows(i).iu; interpretation(i,1)=rows(i).note;
end
master = table(evidenceArea,endpoint,value,unit,independentUnit,interpretation, ...
    'VariableNames',{'EvidenceArea','Endpoint','Value','Unit', ...
    'IndependentUnit','Interpretation'});
writetable(master,fullfile(outDir,'additional_validation_master_summary.csv'));

%% Reviewer-risk evidence matrix
risk = ["Data leakage from random record splitting"; ...
    "Gate threshold and tuning leakage"; ...
    "Elapsed time may be a trivial shortcut"; ...
    "Limited algorithmic baselines"; ...
    "Single-dataset evidence"; ...
    "Sensor faults not sufficiently general"; ...
    "Weak statistical inference"; ...
    "Poor behavior at critical wear"];
validationAdded = ["Strict LOCO plus random-split overlap audit"; ...
    "Outer-training-only nested lambda, gate, and preprocessing selection"; ...
    "Case-wise chronology permutation and test-time time uncertainty"; ...
    "Nested PLS, GPR, SVR, bagging, and LSBoost comparisons"; ...
    "NUAA and PHM2010 label-free run segmentation and grouped validation"; ...
    "Saturation, dropout, bias, and noise injected into multiple sensor channels"; ...
    "Case-level Wilcoxon, Holm adjustment, and case-cluster bootstrap"; ...
    "Wear-band errors plus VB=0.3/0.4 alert metrics and weighted-model falsification"];
status = ["Addressed";"Addressed";"Addressed with claim boundary"; ...
    "Addressed";"Addressed with claim boundary";"Addressed"; ...
    "Addressed";"Quantified; remains a limitation"];
recommendedClaim = ["Use LOCO as primary; random split only demonstrates optimism"; ...
    "State every learned choice is confined to outer training data"; ...
    "Chronology is informative on NASA, but not universally transferable"; ...
    "Ridge gives best pooled MAE; GPR gives best RMSE/R2"; ...
    "External clean time benefit is heterogeneous"; ...
    "Generic quality gating improves corrupted relative MAE by 20.97%"; ...
    "Treat cases/experiments, not signal rows, as independent units"; ...
    "Report 76.9% sensitivity and 80.5% balanced accuracy at VB=0.4"];
riskMatrix = table(risk,validationAdded,status,recommendedClaim, ...
    'VariableNames',{'ReviewerRisk','ValidationAdded','Status','RecommendedClaim'});
writetable(riskMatrix,fullfile(outDir,'reviewer_risk_evidence_matrix.csv'));

%% Consolidated four-panel figure
figure('Color','w','Position',[60 60 1500 980]);
tiledlayout(2,2,'Padding','compact','TileSpacing','compact');

nexttile;
selectedNames=["Primary gated ridge","Quality-aware GPR","Quality-aware PLS", ...
    "Conventional ridge"];
selectedMAE=[primary.MAE;gprRow.MAE; ...
    strongModels.MAE(strongModels.modelNames=="PLSQualityAwareTime");conventional.MAE];
b=bar(selectedMAE,'FaceColor','flat');
b.CData=repmat([0.25 0.55 0.78],4,1); b.CData(1,:)=[0.90 0.30 0.08];
set(gca,'XTickLabel',selectedNames,'XTickLabelRotation',18);
ylabel('MAE'); title('(a) Strict grouped baseline comparison'); grid on;
for i=1:numel(selectedMAE), text(i,selectedMAE(i)+0.001,sprintf('%.3f',selectedMAE(i)), ...
        'HorizontalAlignment','center'); end

nexttile;
permRepeats=readtable(fullfile(outDir,'time_permutation_repeats.csv'), ...
    'VariableNamingRule','preserve');
histogram(permRepeats.MAE,12,'FaceColor',[0.25 0.55 0.78]); hold on;
xline(permSummary.ObservedMAE,'--','Color',[0.90 0.30 0.08], ...
    'LineWidth',2,'Label','Observed');
xlabel('MAE'); ylabel('Permutation count');
title('(b) Case-wise time permutation'); grid on;

nexttile;
bar(uncertainty.MAEChangePercent,'FaceColor',[0.28 0.67 0.46]);
set(gca,'XTickLabel',uncertainty.Scenario,'XTickLabelRotation',18);
ylabel('MAE change (%)'); title('(c) Test-time uncertainty'); grid on;

nexttile;
dsOrder=["NUAA","PHM2010","Combined"];
fullRel=zeros(3,1); autoRel=zeros(3,1);
for i=1:3
    idx=faultStats.Dataset==dsOrder(i);
    fullRel(i)=faultStats.FullRelativeMAE(idx);
    autoRel(i)=faultStats.AutoRelativeMAE(idx);
end
bar([fullRel autoRel]);
set(gca,'XTickLabel',dsOrder); ylabel('Corrupted / clean MAE');
legend({'Full sensors','Automatic quality gate'},'Location','northwest');
title('(d) Multi-fault robustness'); grid on;

sgtitle('Additional Validation under Grouped, Leakage-Controlled Protocols', ...
    'FontWeight','bold');
set(gcf,'ToolBar','none');
allAxes=findall(gcf,'Type','axes');
for axisIndex=1:numel(allAxes)
    if isprop(allAxes(axisIndex),'Toolbar') && ~isempty(allAxes(axisIndex).Toolbar)
        allAxes(axisIndex).Toolbar.Visible='off';
    end
end
drawnow;
exportgraphics(gcf,fullfile(outDir,'additional_validation_overview.png'), ...
    'Resolution',300);
exportgraphics(gcf,fullfile(outDir,'additional_validation_overview.pdf'), ...
    'ContentType','vector');

save(fullfile(outDir,'additional_validation_compiled.mat'), ...
    'master','riskMatrix','mainModels','mainFindings','permSummary', ...
    'uncertainty','highWear','alerts','strongModels','strongStats', ...
    'externalSummary','externalStats','faultStats','cleanGate');

%% Machine-readable artifact manifest
manifestDirs=[string(outDir);string(externalDir);string(faultDir)];
artifactFolder=strings(0,1); artifactName=strings(0,1);
artifactBytes=zeros(0,1); artifactModified=strings(0,1);
for directoryIndex=1:numel(manifestDirs)
    listing=dir(fullfile(manifestDirs(directoryIndex),'*'));
    listing=listing(~[listing.isdir]);
    for fileIndex=1:numel(listing)
        artifactFolder(end+1,1)=manifestDirs(directoryIndex); %#ok<SAGROW>
        artifactName(end+1,1)=string(listing(fileIndex).name); %#ok<SAGROW>
        artifactBytes(end+1,1)=listing(fileIndex).bytes; %#ok<SAGROW>
        artifactModified(end+1,1)=string(listing(fileIndex).date); %#ok<SAGROW>
    end
end
artifactManifest=table(artifactFolder,artifactName,artifactBytes,artifactModified, ...
    'VariableNames',{'Folder','File','Bytes','LastModified'});
writetable(artifactManifest,fullfile(outDir,'validation_artifact_manifest.csv'));

fprintf('\n========== Additional validation package compiled ==========\n');
disp(master);
fprintf('\nSaved to:\n%s\n',outDir);
