paperRoot = fileparts(mfilename('fullpath'));
clear;
clc;
close all;

%% 1. Read saved predictions
resultFolder = ...
    fullfile(paperRoot, 'mill', 'results');

P = readtable(fullfile( ...
    resultFolder, ...
    "sensor_ablation_predictions.csv"));

caseID = P.CaseID;
actualVB = P.ActualVB;
caseList = unique(caseID);

numberOfCases = numel(caseList);

baselinePrediction = ...
    P.Baseline_TimeGated;

sensorNames = [ ...
    "smcAC"; ...
    "smcDC"; ...
    "vib_table"; ...
    "vib_spindle"; ...
    "AE_table"; ...
    "AE_spindle"];

modelColumnNames = [ ...
    "Remove_smcAC"; ...
    "Remove_smcDC"; ...
    "Remove_vib_table"; ...
    "Remove_vib_spindle"; ...
    "Remove_AE_table"; ...
    "Remove_AE_spindle"];

numberOfComparisons = numel(sensorNames);

%% 2. Baseline case-level errors
baselineCaseMAE = nan(numberOfCases,1);
baselineErrorSum = nan(numberOfCases,1);
caseSampleCount = nan(numberOfCases,1);

for caseIndex = 1:numberOfCases

    mask = caseID == caseList(caseIndex);

    currentError = abs( ...
        baselinePrediction(mask)-actualVB(mask));

    baselineCaseMAE(caseIndex) = ...
        mean(currentError);

    baselineErrorSum(caseIndex) = ...
        sum(currentError);

    caseSampleCount(caseIndex) = ...
        sum(mask);
end

baselineOverallMAE = ...
    mean(abs(baselinePrediction-actualVB));

%% 3. Allocate results
removedOverallMAE = ...
    nan(numberOfComparisons,1);

MAEChange = ...
    nan(numberOfComparisons,1);

MAEChangePercent = ...
    nan(numberOfComparisons,1);

improvedCasesAfterRemoval = ...
    nan(numberOfComparisons,1);

worsenedCasesAfterRemoval = ...
    nan(numberOfComparisons,1);

rawPValue = ...
    nan(numberOfComparisons,1);

signedRankStatistic = ...
    nan(numberOfComparisons,1);

bootstrapCILower = ...
    nan(numberOfComparisons,1);

bootstrapCIUpper = ...
    nan(numberOfComparisons,1);

probabilityRemovalWorsens = ...
    nan(numberOfComparisons,1);

removedCaseMAEMatrix = ...
    nan(numberOfCases,numberOfComparisons);

%% 4. Case-clustered bootstrap setup
numberOfBootstrapSamples = 100000;

rng(20260716,"twister");

bootstrapCaseIndex = randi( ...
    numberOfCases, ...
    numberOfCases, ...
    numberOfBootstrapSamples);

bootstrapSampleCount = ...
    sum(caseSampleCount(bootstrapCaseIndex),1);

%% 5. Test each sensor removal
for modelIndex = 1:numberOfComparisons

    prediction = P.(char( ...
        modelColumnNames(modelIndex)));

    removedOverallMAE(modelIndex) = ...
        mean(abs(prediction-actualVB));

    MAEChange(modelIndex) = ...
        removedOverallMAE(modelIndex)- ...
        baselineOverallMAE;

    MAEChangePercent(modelIndex) = ...
        100*MAEChange(modelIndex)/ ...
        baselineOverallMAE;

    removedCaseMAE = ...
        nan(numberOfCases,1);

    removedErrorSum = ...
        nan(numberOfCases,1);

    for caseIndex = 1:numberOfCases

        mask = caseID == caseList(caseIndex);

        currentError = abs( ...
            prediction(mask)-actualVB(mask));

        removedCaseMAE(caseIndex) = ...
            mean(currentError);

        removedErrorSum(caseIndex) = ...
            sum(currentError);
    end

    removedCaseMAEMatrix(:,modelIndex) = ...
        removedCaseMAE;

    caseDifference = ...
        removedCaseMAE-baselineCaseMAE;

    % Negative difference: removal improves performance
    improvedCasesAfterRemoval(modelIndex) = ...
        sum(caseDifference < 0);

    worsenedCasesAfterRemoval(modelIndex) = ...
        sum(caseDifference > 0);

    [rawPValue(modelIndex),~,statistics] = ...
        signrank( ...
        removedCaseMAE, ...
        baselineCaseMAE, ...
        "method","exact");

    if isfield(statistics,"signedrank")
        signedRankStatistic(modelIndex) = ...
            statistics.signedrank;
    end

    % Clustered bootstrap difference:
    % removed model MAE - baseline MAE
    bootstrapDifference = ...
        (sum(removedErrorSum( ...
        bootstrapCaseIndex),1) - ...
        sum(baselineErrorSum( ...
        bootstrapCaseIndex),1)) ./ ...
        bootstrapSampleCount;

    confidenceInterval = ...
        prctile( ...
        bootstrapDifference,[2.5 97.5]);

    bootstrapCILower(modelIndex) = ...
        confidenceInterval(1);

    bootstrapCIUpper(modelIndex) = ...
        confidenceInterval(2);

    probabilityRemovalWorsens(modelIndex) = ...
        mean(bootstrapDifference > 0);
end

%% 6. Holm multiple-comparison correction
[sortedPValue,sortingIndex] = ...
    sort(rawPValue);

adjustedSortedP = ...
    nan(numberOfComparisons,1);

runningMaximum = 0;

for sortedIndex = 1:numberOfComparisons

    correctionFactor = ...
        numberOfComparisons-sortedIndex+1;

    currentAdjustedP = min( ...
        1, ...
        correctionFactor * ...
        sortedPValue(sortedIndex));

    runningMaximum = max( ...
        runningMaximum,currentAdjustedP);

    adjustedSortedP(sortedIndex) = ...
        runningMaximum;
end

holmAdjustedP = ...
    nan(numberOfComparisons,1);

holmAdjustedP(sortingIndex) = ...
    adjustedSortedP;

significantAfterHolm = ...
    holmAdjustedP < 0.05;

%% 7. Summary table
statisticalResults = table( ...
    sensorNames, ...
    removedOverallMAE, ...
    MAEChange, ...
    MAEChangePercent, ...
    improvedCasesAfterRemoval, ...
    worsenedCasesAfterRemoval, ...
    rawPValue, ...
    holmAdjustedP, ...
    significantAfterHolm, ...
    signedRankStatistic, ...
    bootstrapCILower, ...
    bootstrapCIUpper, ...
    probabilityRemovalWorsens, ...
    'VariableNames', ...
    {'RemovedSensor', ...
     'RemovedModelMAE', ...
     'MAEChange', ...
     'MAEChangePercent', ...
     'CasesImprovedAfterRemoval', ...
     'CasesWorsenedAfterRemoval', ...
     'RawPValue', ...
     'HolmAdjustedP', ...
     'SignificantAfterHolm', ...
     'SignedRankStatistic', ...
     'BootstrapCILower', ...
     'BootstrapCIUpper', ...
     'ProbabilityRemovalWorsens'});

fprintf("========== Sensor ablation statistics ==========\n");
fprintf("Baseline TimeGated MAE: %.6f\n\n", ...
    baselineOverallMAE);

disp(statisticalResults);

fprintf( ...
    "Positive MAEChange means removal worsened performance.\n");

fprintf( ...
    "Negative MAEChange means removal improved performance.\n");

%% 8. Plot with clustered confidence intervals
fig = figure( ...
    "Color","w", ...
    "Position",[100 100 1250 580]);

xPosition = 1:numberOfComparisons;

bar(xPosition,MAEChange, ...
    "FaceColor",[0.20 0.55 0.80]);

hold on;

lowerError = ...
    MAEChange-bootstrapCILower;

upperError = ...
    bootstrapCIUpper-MAEChange;

errorbar( ...
    xPosition,MAEChange, ...
    lowerError,upperError, ...
    "k", ...
    "LineStyle","none", ...
    "LineWidth",1.3);

yline(0,"k--","LineWidth",1.2);

for modelIndex = 1:numberOfComparisons

    if significantAfterHolm(modelIndex)

        if MAEChange(modelIndex) >= 0
            textSymbolHeight = ...
                bootstrapCIUpper(modelIndex)+0.001;
        else
            textSymbolHeight = ...
                bootstrapCILower(modelIndex)-0.001;
        end

        text( ...
            modelIndex,textSymbolHeight,"*", ...
            "HorizontalAlignment","center", ...
            "FontSize",16, ...
            "FontWeight","bold");
    end
end

hold off;
grid on;

xticks(xPosition);
xticklabels(sensorNames);

ax = gca;
ax.TickLabelInterpreter = "none";

xlabel("Removed sensor");
ylabel("MAE change relative to TimeGated");

title("Statistical Analysis of Sensor Ablation");

subtitle( ...
    "Error bars: case-clustered 95% confidence intervals");

%% 9. Save
writetable( ...
    statisticalResults, ...
    fullfile(resultFolder, ...
    "sensor_ablation_statistics.csv"));

save( ...
    fullfile(resultFolder, ...
    "sensor_ablation_statistics.mat"), ...
    "statisticalResults", ...
    "baselineCaseMAE", ...
    "removedCaseMAEMatrix");

exportgraphics( ...
    fig, ...
    fullfile(resultFolder, ...
    "sensor_ablation_statistics.png"), ...
    "Resolution",300);